### ISSUE TITLE
CDN URLs not working

### ISSUE THREAD

**Issue by dragondgold** [uuidjs/uuid#364]
The links to `https://unpkg.com/uuid@latest/dist/umd/uuidv4.min.js` and `https://cdn.jsdelivr.net/npm/uuid@latest/dist/umd/uuidv4.min.js` to use in the browser are not working!

**Comment by ctavan** [comment]
@dragondgold as written in the current README, the current READEM already refers to the next major release of this library which will be v7.0.0.

The current stable release v3.4.0 does not offer built-in support to load the library from a CDN. As detailed out [in other issues there are workarounds though](https://github.com/uuidjs/uuid/issues/302#issuecomment-524827935).

Alternatively you could try the beta release of v7.0.0 until we release it as "latest": `https://unpkg.com/uuid@beta/dist/umd/uuidv4.min.js`

**Comment by dragondgold** [comment]
Thank you @ctavan :)

**Comment by ctavan** [comment]
We have just released [`uuid@7.0.0`](https://github.com/uuidjs/uuid/blob/v7.0.0/CHANGELOG.md#700-2020-02-24) which now features direct UMD builds again: https://github.com/uuidjs/uuid#umd-builds

Please feel free to open a new issue if you encounter any issues with the new version.
