### ISSUE TITLE
Drop the default export?

### ISSUE THREAD

**Issue by ctavan** [uuidjs/uuid#370]
In `uuid@3.x` the Version 4 algorithm was exported as a default:

```js
const uuid = require('uuid');
uuid(); // -> "2b0d20b0-6462-4738-abe6-413512e9fbf2"
```

In the current master this is no longer the case:

```js
const uuid = require('uuid');
uuid(); // -> Uncaught TypeError: uuid is not a function
uuid.v4() // -> "ea58b65b-80c4-44c6-b482-6714c78ac43e"
```

The minimum we should probably do is describe this in the README and in the CHANGELOG.

I could also try to use the data from https://github.com/tc39/proposal-uuid/tree/master/analysis in order to try to figure out how much of a breakage removing the default export would be?!

What do you think about this breaking change @broofa?

**Comment by broofa** [comment]
Finally, an actual breaking change!  ;-)   (I'm fine with this since we've been actively discouraging people from using a default export since v3.)

**Comment by ctavan** [comment]
Cool! I only found out about this breaking change now while writing the TypeScript types, so it looks like you did a great job at discouraging it's use 😂!

I will still add a note to the upgrading section in the readme though and will make sure that this breaking change appears in the CHANGELOG.

**Comment by Raynos** [comment]
I would recommend leaving a human readable exception in place for user experience.

**Comment by CaptainFalcon92** [comment]
Why aren't export an actual uuid lib/wrapper object ? so we could do

`import uuid from 'uuid';`

`    this.id = new uuid.v4()`
`    this.id = uuid.parse(res.id)`

Like any other lib would.
That would have been so much better.

Now we must write

`import { v4 as uuidv4, parse as uuidParse, stringify as uuidStringify } from 'uuid';`
why do this?.
