### ISSUE TITLE
v3.4.0 to v7.0.0 ?

### ISSUE THREAD

**Issue by fraxken** [uuidjs/uuid#376]
Hi,

Is there is a mistake with the major number of the new version ? Or there is a reason to not go with major 4 etc ?

Best Regards,
Thomas

**Comment by broofa** [comment]
https://github.com/uuidjs/uuid/blob/master/README.md#upgrading-from-uuid3

**Comment by crfrolik** [comment]
FYI doing this sort of version skipping actually violates the semver spec, if you care about that sort of thing.  https://semver.org/#spec-item-2

(I also found it more confusing than having a version 4 of the module)

**Comment by ctavan** [comment]
@crfrolik what aspect of semver does leaving out certain major versions violate?

**Comment by broofa** [comment]
Semver doesn't prohibit skipping major versions.  Cited item #2 specifies version string form ("X.Y.Z"), provides no credibility to @crfrolik's claim.
