### ISSUE TITLE
version 7.0.0 doesn't work with react

### ISSUE THREAD

**Issue by nemoload** [uuidjs/uuid#379]
`import { v1 as uuidv1 } from 'uuid'`

gives this error:
```
Failed to compile.

./node_modules/uuid/index.js
Error: ENOENT: no such file or directory, open '/home/akhal3d/webapp/node_modules/uuid/index.js'
```

**Comment by TrySound** [comment]
Check which version do you have in `/home/akhal3d/webapp/node_modules/uuid/package.json`?

**Comment by ctavan** [comment]
@nemoload the error you show does not seem to relate to this library. Have you tried to remove your `node_modules/` directory and run `npm install` again?

Please provide the exact steps to reproduce your error.

**Comment by nemoload** [comment]
@TrySound 
> Check which version do you have in /home/akhal3d/webapp/node_modules/uuid/package.json?

`"uuid": "^7.0.0"`

**Comment by nemoload** [comment]
> @nemoload the error you show does not seem to relate to this library. Have you tried to remove your `node_modules/` directory and run `npm install` again?
> 
> Please provide the exact steps to reproduce your error.

I have just did this and everything works fine now! I have no idea why this happened in the first place. Thank you all for your help and response.
