### ISSUE TITLE
DeprecationWarning: Deep requiring like `const uuidv4 = require('uuid/v4');` is deprecated as of uuid@7.x. Please require the top-level module when using the Node.js CommonJS module or use ECMAScript Modules when bundling for the browser. See https://github.com/uuidjs/uuid/blob/master/README.md#upgrading-from-v3x-of-this-module for more information.

### ISSUE THREAD

**Issue by goxr3plus** [uuidjs/uuid#381]
I am getting the above error why :) ? Using the latest version `7.0.0`

**Comment by TrySound** [comment]
@goxr3plus https://github.com/uuidjs/uuid/blob/master/CHANGELOG.md#700-2020-02-24

**Comment by ctavan** [comment]
@goxr3plus please refer [to this section in the README](https://github.com/uuidjs/uuid#deep-requires-now-deprecated) on more information upgrading this module from `3.x` to `7.x`
