### ISSUE TITLE
Invite @LinusU to uuidjs org

### ISSUE THREAD

**Issue by ctavan** [uuidjs/uuid#394]
@broofa opening this issue simply to document the fact that I have invited @LinusU to the uuidjs org as he has volunteered to help with reviews in https://github.com/uuidjs/uuid/pull/390#issuecomment-593539772 😉 

Welcome @LinusU 🎉 !

We prefer if members of the uuidjs org make their membership public and we require 2FA to be enabled.

**Comment by LinusU** [comment]
Thank you! 🎉 

I've made the membership public and have 2FA enabled ☺️
