### ISSUE TITLE
ELOOP: too many symbolic links encountered

### ISSUE THREAD

**Issue by dattajoshi** [uuidjs/uuid#403]
Hi,

I'm trying push my node code using aws-amplify, But I'm getting this error 

ELOOP: too many symbolic links encountered, stat '/Users/project/amplify/backend/function/function/src/node_modules/uuid'
An error occured during the push operation: ELOOP: too many symbolic links encountered, stat '/Users/project/amplify/backend/function/function/src/node_modules/uuid'

Any help is appreciated 

Using
node: v12.3.1
npm: 4.6.1

Thanks

**Comment by ctavan** [comment]
At a first glance this doesn’t look like an obvious problem with this library, rather something in the specific npm/project setup.

Could you please provide detailed steps to reproduce the issue?

**Comment by dattajoshi** [comment]
Thanks for checking, yeah the issue was with npm, the uuid packages wasn't packaged properly.
I fixed it.

Thanks though
