### ISSUE TITLE
Drop Node.js 8.x support

### ISSUE THREAD

**Issue by ctavan** [uuidjs/uuid#410]
Node.js 8.x [reached EOL on 2019-12-31](https://github.com/nodejs/Release#end-of-life-releases).

Many of our development dependencies (prettier, rollup) already removed support for Node 8.x.

I would like to remove official support for node 8.x as well. This will require a major version bump.

Thoughts?

**Comment by broofa** [comment]
Do it.  There's already precedent for only supporting maintained node releases in the form of #275.

**Comment by ctavan** [comment]
As pointed out by @broofa, in #275 the preferred policy was "supported node versions + one legacy version".

This seems to make sense as long as popular runtimes like [Google Cloud Functions](https://cloud.google.com/functions/docs/concepts/nodejs-8-runtime) still support Node.js 8.x

**Comment by TrySound** [comment]
Looks like google cloud packages are almost all migrated away from node 8.

**Comment by ctavan** [comment]
@TrySound thanks for the notice.

I still think that, given the wide adoption of this module, the "supported node versions + 1 unsupported" is still a good policy and puts less pressure on the ecosystem.
