### ISSUE TITLE
Import error using Node with ES6 syntax

### ISSUE THREAD

**Issue by th1j5** [uuidjs/uuid#419]
## Was a bug report about using ES6 import syntax in Node

Since seeing this #245 (the last comments),
I would suggest updating the readme to explicitly state that it's not (yet #402 ) supported for Node.
This would prevent people from losing time on writing unnecessary bug reports ;)

Thanks!

**Comment by ctavan** [comment]
@th1j5 we have just released `uuid@8.0.0` which comes with native ESM support for Node.js! Let us know if that works for you.

**Comment by th1j5** [comment]
Like a charm!
