### ISSUE TITLE
No valid exports main found for '...\node_modules\uuid'

### ISSUE THREAD

**Issue by Leandro-Albano** [uuidjs/uuid#428]
## Describe the bug

Just installed version "8.0.0" and I'm experiencing the following behavior
Trying to import the lib this way
`import { v4 as uuidv4 } from "uuid";`

and getting 
`No valid exports main found for '...\node_modules\uuid'`

Rolling back to "7.0.3" it works fine.

## Expected behavior

The lib should work fine.

## Runtime

- OS: Windows
- Runtime: Node.js
- Runtime Version: 13.5

**Comment by TrySound** [comment]
What do you use to transpile es modules to commonjs?

**Comment by TrySound** [comment]
@ctavan this is another way of providing exports
https://unpkg.com/browse/nanoevents@5.1.5/package.json

**Comment by Leandro-Albano** [comment]
I'm using just typescript.

**Comment by TrySound** [comment]
ts-node or tsc?

**Comment by TrySound** [comment]
This issue looks similar https://github.com/ai/nanoid/issues/206#issuecomment-612222877

**Comment by Leandro-Albano** [comment]
ts-node

**Comment by TrySound** [comment]
Check the link. Update to the latest node 13

**Comment by Leandro-Albano** [comment]
Cool, thank you so much, that worked!

**Comment by ctavan** [comment]
FTR: We explicitly decided *not* to support early 13.x versions of Node.js where the `exports` field of `package.json` behaved slightly different (see https://github.com/uuidjs/uuid/pull/402#discussion_r389348264).

**Comment by antoniandre** [comment]
Hi, is this resolved?
I get the same error trying to install a new package, on node version 14.4.0 and npm version 6.14.5 (latests).
https://github.com/release-it/release-it/issues/674

**Comment by ctavan** [comment]
See https://github.com/release-it/release-it/issues/674#issuecomment-641955575
