### ISSUE TITLE
Add @TrySound as maintainer

### ISSUE THREAD

**Issue by ctavan** [uuidjs/uuid#432]
@TrySound  you keep answering issues in this repo faster than me and you are providing so much valuable feedback. Thank you so much!

While I would still reserve the last say about PR merges and releases to @broofa and me  I would be happy to invite you as a maintainer to this repo so that you could closed issues and review PRs yourself. Of course only if you want that!

@broofa, @LinusU any objections?

**Comment by TrySound** [comment]
Thanks! I'm glad to help

**Comment by broofa** [comment]
<a href="https://gitme.me/image?url=https%3A%2F%2Fmedia3.giphy.com%2Fmedia%2Fl0Ex39XVJoz6Wfh6w%2Fgiphy.gif&token=sure" data-gitmeme-token="sure"><img src="https://media3.giphy.com/media/l0Ex39XVJoz6Wfh6w/giphy.gif" title="Created by gitme.me with /sure"/></a>

**Comment by LinusU** [comment]
![](https://media.giphy.com/media/9Ai5dIk8xvBm0/source.gif)

**Comment by ctavan** [comment]
Welcome @TrySound!

As a matter of transparency: Would you mind making your membership of the UUID org public?

**Comment by TrySound** [comment]
Thanks! Fixed
