### ISSUE TITLE
version 8.0.0 is not working with typescript

### ISSUE THREAD

**Issue by frascaluigi** [uuidjs/uuid#441]
## Describe the bug

`import { v4 as uuid } from 'uuid'`

don't work in my project with typescript 3.8.3 

## Error

`No valid exports main found for '/Users/Luigi/Documents/projects/test/node_modules/uuid`

## Runtime

- macOS
- Node.js versione 13.6

**Comment by ctavan** [comment]
Node.js verison 13.6 is pretty old and not supported by UUID v8.x, upgrade to a later version of Node.js 13.x, or to Node.js 14.x.

see #428

**Comment by mattsains** [comment]
Given that the current node LTS version is 12.16, I'm not sure it's fair to say that 13.6 is "pretty old"

**Comment by broofa** [comment]
@mattsains It's not old in human time (13.6 was released 2020-01-07) but it's old in the node-release cycle sense.  It's eight minor releases behind the latest v13 release.  It's also old in the overall sense that odd-numbered releases are only supported for six months, and v13 will be [EOL'ed at the end of this month](https://nodejs.org/en/about/releases/).

**Comment by ctavan** [comment]
What I intended to say was what @broofa explained: you should not expect library authors to support _experimental_ APIs of outdated versions of non-LTS releases of Node.js. If you choose to run on non-LTS then at least make sure to upgrade to the latest available Node.js version before bothering library authors.
