### ISSUE TITLE
Crazy Version Jump… 3.4 > 7.0 What happened?

### ISSUE THREAD

**Issue by martnst** [uuidjs/uuid#446]
Hi *, 

as I was running `yarn outdated` I was surprised how this package could go from version 3.4 to 8.0 in relatively short time. Checking the [CHANGELOG](https://github.com/uuidjs/uuid/blob/master/CHANGELOG.md) I noticed that 3 Majors were skipped. Unfortunately it does not explain why, though. 

Bests, 
Martin 

![image](https://user-images.githubusercontent.com/3084607/81574678-6a918f80-93a6-11ea-8497-a131370dc48d.png)

**Comment by ctavan** [comment]
See https://github.com/uuidjs/uuid#upgrading-from-uuid3
