### ISSUE TITLE
uuid error

### ISSUE THREAD

**Issue by satyendrasingh8** [uuidjs/uuid#447]
uncaught typeError: (0 , _uuid.default) is not a function

## To Reproduce

1. Install '...'
2. Run '....'
3. See error

## Runtime

- OS: [e.g. macOS, Linux]
- Runtime: [e.g. Node.js, Chrome, Safari, react-native, AWS Lambda]
- Runtime Version: [e.g. 14.2.0]

**Comment by satyendrasingh8** [comment]
uncaught typeError: (0 , _uuid.default) is not a function

**Comment by LinusU** [comment]
How are you importing uuid?

**Comment by ctavan** [comment]
See https://github.com/uuidjs/uuid/issues/448#issuecomment-628028997
