### ISSUE TITLE
"main" parameter missing from package.json in V3.4.0 NPM package

### ISSUE THREAD

**Issue by jimtendo** [uuidjs/uuid#461]
## Describe the bug

The README.md found on npmjs.com (https://www.npmjs.com/package/uuid) suggests that the library can be used as a CommonJS module as follows (as of NPM package version 8.1.0):

```
const { v4: uuidv4 } = require('uuid');
```

However, on Node v11.10.1 this yields the error:

```
Error: Cannot find module 'uuid'
```

It looks like the NPM package.json is missing the "main" field that should point to `/dist/index.js`

## To Reproduce

1. Install 'npm install uuid --save'
2. Run a node script that contains `const uuid = require('uuid')
3. See `Error: Cannot find module 'uuid'`

## Expected behavior

The module should be found when doing:

```
const uuid = require('uuid')
```

## Runtime

- OS: Linux
- Runtime: Node
- Runtime Version: v11.10.1
- NPM package version: 8.1.0

**Comment by TrySound** [comment]
Hi, "main" field is not missing
https://unpkg.com/browse/uuid@8.1.0/package.json

Your error looks like the package was not really installed. Please check `./node_modules/uuid/package.json`. Which version do you see?

**Comment by ctavan** [comment]
1. I cannot reproduce the issue, even with Node.js v11.10.1. Please make sure that the npm package is actually installed by looking at `./node_modules/uuid`. Or try reinstalling them: `rm -rf ./node_modules && npm install`
2. The `v11.x` release of Node.js is outdated and unsupported. This library only officially supports LTS releases of Node.js (v8, v12, v14). Please check https://nodejs.org/en/about/releases/ for details on Node.js versioning semantics.
