### ISSUE TITLE
Drop IE11 support

### ISSUE THREAD

**Issue by ctavan** [uuidjs/uuid#469]
I believe we should drop IE11 support with the next major release. This would allow us to produce much more modern bundles.

As of June 2020 IE11 market share is only 1.4% according to https://gs.statcounter.com/

Users who really need to support IE11 would still be able to transpile our bundles or add required polyfills.

As part of this we can remove `output.ecmaVersion: 5` from the webpack configs.

**Comment by broofa** [comment]
> Users who really need to support IE11 would still be able to transpile our bundles or add required polyfills.

... or pin their dependency to  `uuid@v3.4.0`

**Comment by fzxt** [comment]
I recently saw some issues in IE11 browsers w.r.t trailing commas. Specifically with the `node_modules/uuid/v4.js` module. Not sure if anyone else has experienced this recently / can comment on this.

**Comment by ctavan** [comment]
@fzxt can you provide more details? This is definitely not expected: First of all, the most recent version of this library doesn't even expose a `node_modules/uuid/v4.js` module, second we make sure to transpile the browser-targeted code to work well with IE11.

**Comment by fzxt** [comment]
@ctavan just to close the loop on this, we were indeed on some old version and the errors were due to some custom setup. Sorry to necro / distract on this issue.

**Comment by broofa** [comment]
FYI, MSFT dropping IE11 support for MS 365 in August 2021.  [Source](https://docs.microsoft.com/en-us/lifecycle/announcements/internet-explorer-11-support-end-dates)

**Comment by broofa** [comment]
Update...

IE11 now at 0.47% market share (Aug 2021, [source](https://gs.statcounter.com/browser-version-partially-combined-market-share#monthly-202008-202108)).

From [this page](https://docs.microsoft.com/en-us/lifecycle/products/internet-explorer-11):

> The Internet Explorer (IE) 11 desktop application will end support for certain operating systems starting June 15, 2022. Customers are encouraged to move to Microsoft Edge with IE mode. IE mode enables backward compatibility and will be supported through at least 2029.

**Comment by ctavan** [comment]
Does that mean that folks running edge in IE mode need the same level of compatibility as IE11? 🤔

**Comment by Rush** [comment]
And users needing IE11 can still transpile whatever they need via webpack + babel.
