### ISSUE TITLE
Add types

### ISSUE THREAD

**Issue by Shahaed** [uuidjs/uuid#470]
Add types for this package. Simple type definition already exists: https://www.npmjs.com/package/@types/uuid. Incorporating it into this repo would be really helpful.

**Comment by ctavan** [comment]
This has been discussed in the past but as long as this library is written in JavaScript we're going to continue to publish the types as a separate package, see https://github.com/uuidjs/uuid/issues/368#issuecomment-587330334

In fact the maintainers of `uuid` are maintaining `@types/uuid` as well!

**Comment by Shahaed** [comment]
Most other popular npm packages include types in the same package and saves typescript users from having to import 2 packages. Also makes maintenance easier.

My vote would be including types in the same package, but it's y'all decision.

**Comment by ctavan** [comment]
Feel free to raise this issue over at TypeScript. If TypeScript decides to change their recommendations, I'll be happy to follow whatever the official recommendations are.
