### ISSUE TITLE
Reopened discussion: parse/unparse uuid

### ISSUE THREAD

**Issue by IsaiahJTurner** [uuidjs/uuid#478]
In the past, requests for the ability to parse/unparse UUIDs have been closed with a referral to https://www.npmjs.com/package/uuid-parse

I am aware and agree that this use case is relatively uncommon when compared to the overall use of UUIDs. However, this module is now archived with a notice that "This module is no longer maintained"

It is not even possible to file an issue or view issues on that project which makes it unfit for safe usage. My preference would be for the functionality to simply be merged into this package. However, given the strong reluctance to do that in the past, perhaps uuidjs could take over management of that module or host the same functionality in a new module?

**Comment by ctavan** [comment]
@IsaiahJTurner thanks for raising this issue. We have in fact already added parsing and validation in the `v9` branch of this module: https://github.com/uuidjs/uuid/tree/v9

I can try to put a pre-release out so you can try it out.

**Comment by ctavan** [comment]
@broofa so far, it doesn't look like the `v9` branch contains any breaking changes: https://github.com/uuidjs/uuid/compare/v9

I only see the addition of parse and validate methods.

Am I missing something? If not we could just release that as `8.2.0` (maybe a `-beta` prerelease first)? WDYT?

**Comment by ctavan** [comment]
@IsaiahJTurner we have just released `uuid@8.3.0-beta.0` which includes https://github.com/uuidjs/uuid#uuidparsestr and https://github.com/uuidjs/uuid#uuidstringifyarr-offset would you mind testing it and report if that works for you?

**Comment by ctavan** [comment]
We have just released `uuid@8.3.0` which should fix this issue. Please report back if there any problems.
