### ISSUE TITLE
toBytes

### ISSUE THREAD

**Issue by xenoterracide** [uuidjs/uuid#481]
we have need for decoding the standard uuid format to just the bytes, the reason for this is we want to re-encode as url encoded base64 to shorten our urls. note, if you wanted to provide a function for that as well... use something like

`base64( toBytes( uuidv4() ) )`

also an inverse

`fromBytes`

**Comment by ctavan** [comment]
We'll release this soon, see #479

**Comment by ctavan** [comment]
@xenoterracide we have just released `uuid@8.3.0-beta.0` which includes https://github.com/uuidjs/uuid#uuidparsestr would you mind testing it and report if that works for you?

**Comment by ctavan** [comment]
We have just released `uuid@8.3.0` which should fix this issue. Please report back if there any problems.
