### ISSUE TITLE
UUID reference error

### ISSUE THREAD

**Issue by rashidvali** [uuidjs/uuid#482]
## Describe the bug

Whe I run my app in a browser it throws "Uncaught ReferenceError: require is not defined", complaining to: Object.crypto (external "crypto":1)

## To Reproduce

1. Install 'npm install uuid'
2. Run ' // In  my module I import it:
import { v4 as uuid4 } from 'uuid';
....
// and then call the function
let id: string = uuid4();
'
3. See error: // It complains
external "crypto":1 Uncaught ReferenceError: require is not defined
    at Object.crypto (external "crypto":1)
    at __webpack_require__ (bootstrap:19)
    at Module../node_modules/uuid/dist/esm-node/rng.js (rng.js:1)
    at __webpack_require__ (bootstrap:19)
    at Module../node_modules/uuid/dist/esm-node/v1.js (v1.js:1)
    at __webpack_require__ (bootstrap:19)
    at Module../node_modules/uuid/dist/esm-node/index.js (index.js:1)
    at __webpack_require__ (bootstrap:19)
    at Object../src/Conn/InnerStruct/ConnStruct.ts (ConnStruct.ts:1)
    at __webpack_require__ (bootstrap:19)

## Expected behavior
It should return a Universally unique id

## Runtime

- OS: Windows 10
- Runtime: Crome v.83.0.4103.116

## Additional context
TypeScript/Webpack project with Node v12.18.2

As long as I can understand a 'crypto' dependency is a reason for the trouble

**Comment by ctavan** [comment]
What webpack version and confit are you using? Please provide everything that is required to reproduce the issue.

**Comment by rashidvali** [comment]
webpack v.4.43.0

**Comment by rashidvali** [comment]
I have the following in the package.json:

  "devDependencies": {
    "@types/lodash": "^4.14.107",
    "ts-loader": "^8.0.1",
    "typescript": "^3.9.7",
    "typings-for-css-modules-loader": "^1.7.0",
    "webpack": "^4.43.0",
    "webpack-cli": "^3.3.12",
    "webpack-dev-server": "^3.11.0",
    "@types/uuid": "^8.0.0"
  },

**Comment by rashidvali** [comment]
and

  "dependencies": {
    "@types/node": "^14.0.23",
    "css-loader": "^1.0.0",
    "node-sass": "^4.14.1",
    "sass-loader": "^7.1.0",
    "style-loader": "^0.23.1",
    "uuid": "^8.2.0"
  }

**Comment by rashidvali** [comment]
It looks like not UUID package own problem. That is Node.js crypto (node_modules/crypto-browserify) problem. I am getting the same error when I call crypto methods.

**Comment by ctavan** [comment]
Something seems off with your webpack config. Are you building for Node.js or for the Browser? For browser environments, webpack should pick up the _browser build_ of this library, which has no dependency to the Node.js crypto API. Instead, webpack seems to be trying to pull in the browserify crypto API polyfill, which is totally not what should happen.

Please have a look at https://github.com/uuidjs/uuid/blob/master/examples/browser-webpack/webpack.config.js and https://github.com/uuidjs/uuid/blob/master/examples/node-webpack/webpack.config.js for working webpack configs.

**Comment by ctavan** [comment]
Please feel free to re-open if you believe that this is a problem with this library rather than with your specific webpack setup.

**Comment by rashidvali** [comment]
Is there any other way of installing uuid aside of 'npm install uuid'? How installation for the browser environment is different from an installation for node? And I don't see anything wrong in my webpack.

**Comment by ctavan** [comment]
It's not about how you install `uuid` through npm, it's about what files webpack will pick up. This is controlled by the webpack config [`resolve.mainFields`](https://v4.webpack.js.org/configuration/resolve/#resolvemainfields). For a browser build, webpack _should_ pick up a browser-specific build that is included in the `uuid` npm package. However judging from your error output, webpack instead picks up the Node.js build (see `dist/esm-node` paths in your error output). This should only happen when you use webpack to bundle for a Node.js environment, but then webpack _should not_ try to include polyfills for Node.js APIs…

Without your full webpack config and the exact commands that you are running to produce the above error I fear I won't be able to provide any more meaningful help.

**Comment by rashidvali** [comment]
here is my webpack, could it help?:

const path = require('path');
const webpack = require('webpack');

module.exports = {
    entry: "./src/init.ts",
    mode: 'development',
    devtool: "source-map",
    // devtool: 'inline-source-map',    
    module: {
        rules: [
            {
                test: /\.ts?$/,
                 use: 'ts-loader',
                exclude: /node_modules/,
                include: /src/,
            },
            {
                test: /\.s?css/, 
                use: [
                    "style-loader", 
                    {
                        loader: 'typings-for-css-modules-loader',
                        options: {
                          modules: true,
                          namedExport: true
                        }
                    },
                ]
            }
        ]
    },
    resolve: {
        extensions: ['*', '.ts', '.js'],
    },
    output: {
        filename: 'bundle.js',
        path: __dirname + '/dist',
    },
    target: "node",
};

**Comment by ctavan** [comment]
Hmm, it does have `target: "node"`, so it's correct that webpack pulls in the node build of `uuid`. I still don't understand why webpack tries to load the `crypto-browserify` polyfill.

I think this is rather a topic for the webpack issue tracker, I'm sorry.
