### ISSUE TITLE
Need a static error codes for their identification

### ISSUE THREAD

**Issue by awwit** [uuidjs/uuid#487]
When throwing an exception, we need short and unchanging error codes. To be able to accurately identify the error without resorting to parsing the error message.

for example:

```js
const { v1 as uuidv1 } = require('uuid');

const array = new Array(16);

try {
  uuidv1(null, array, 0);
} catch (err) {
  if (err.code === 'UUID_V1_RATE_LIMIT_PER_SEC') {
    // Do something
  }
}
```

**Comment by broofa** [comment]
I'm going to argue we *not* do this.

`code` isn't a standard `Error` property, it's merely a node.js convention and (I suspect) not particularly well adopted outside of the core node.js codebase.  While it does make identifying `Error`s easier... so what?   JS devs are used to dealing with Errors that don't have codes.  Prior to this issue, nobody has asked for them.  Thus, the utility does not seem particularly high. (Personally, I wasn't even aware node errors had codes until recently. 😊 )

Also, in the cases where I have seen `err.code` used, it's generally as a forwarding mechanism for codes that are an intrinsic part of underlying services of some sort.  E.g. modules that wrap HTTP or FTP interfaces, where status codes are an important part of the protocol.  We don't have that here.   The RFC does not specify any sort of error or status codes, so we would be inventing our own for this, which (imho) unnecessarily complicates things.

Finally, they're a bit of a pain to implement.  With the simplest ad-hoc approach, we end up with code like this:
```
if (condition) {
  throw new Error(...);
}
```
... turning into this everywhere:
```
if (condition) {
  const err = new Error(...);
  err.code = SOME_ERROR_CODE;
  throw err;
}
```

Of course we could implement a helper function of some sort, but that's not exactly trivial (e.g. IE11 doesn't support the `...` operator, so forwarding arguments to the `Error` constructor is somewhat problematic).

If you dig into nodejs to see what kind of "helper" they use, it's actually pretty impressive.  Errors are instantiated via the code, not the  class.  E.g. `new ERR_FS_FILE_TOO_LARGE(size)`.  But the internal scaffolding needed to allow that is rather daunting.

**Comment by awwit** [comment]
@broofa you probably misunderstood me.
I would like to have error codes only for those exceptions that you throw yourself.

This does not require an operator `...`. You just need to add error codes.

It doesn't matter that the `err.code` is not standardized. It is much more important that the error code is a needful and useful property.

How could it be otherwise?
How do you suggest to handle the exceptions thrown by the library?

**Comment by broofa** [comment]
> you probably misunderstood me

I think I do... I'm just not convinced differentiating  between errors at this level is a real problem for users of this module.

Please give me some real-world examples of why this is necessary and convince me otherwise.

> How do you suggest to handle the exceptions thrown by the library?

The same as exceptions from any of the other 100,000's of modules that don't provide `.code`s.

**Comment by awwit** [comment]
@broofa hmm you are right.

I looked at the source code of the library again and saw that at most one exception is thrown in each individual function.

So I close the issue =)
