### ISSUE TITLE
Documented "validate" function not available

### ISSUE THREAD

**Issue by Kmaschta** [uuidjs/uuid#494]
## Describe the bug

The `uuid.validate` function is documented on the README, but is not available on the latest versions of the package.

## To Reproduce

1. Install `uuid@8.2.0`
2. Run `import { validate } from 'uuid'`
3. See error `Attempted import error: 'validate' is not exported from 'uuid' (imported as 'validate').`

## Expected behavior

I would like to validate my UUIDs.

## Runtime

- Runtime: Every runtimes

**Comment by TrySound** [comment]
It's in beta
https://unpkg.com/browse/uuid@8.3.0-beta.0/

**Comment by ctavan** [comment]
If you could try out the beta and report it it works for you that would be awesome! Will release once we have received some positive feedback.

**Comment by Kmaschta** [comment]
So, I've used the beta version in my app to validate the UUID, thanks for your answers, and sorry for my impatience!
I'll definitely share my feedback as soon as this reach the production :)

**Comment by Kmaschta** [comment]
Here's more news from me :)
We used the `8.3.0-beta.0` version on production, and it's going fine !
Looking forward to upgrade as soon as it reaches the final release

**Comment by TrySound** [comment]
It did https://github.com/uuidjs/uuid/releases/tag/v8.3.0
