### ISSUE TITLE
Dependency requirements bullshit

### ISSUE THREAD

**Issue by stupidkitty** [uuidjs/uuid#499]
Are you crazy?

Got an error: _crypto.getRandomValues() not supported. See https://github.com/uuidjs/uuid#getrandomvalues-not-supported_

After studying the code, I discovered incredible! Recommended polyfill requires React-native installation. WTF?

**Comment by TrySound** [comment]
Read carefully again. First cases describes how to solve the problem in react-native, the second in web workers. If you have the problem with another environment. Please open an issue with full description. We will not help if you are rude.
![image](https://user-images.githubusercontent.com/5635476/88714250-3025cc00-d125-11ea-80ff-d3e3624ecb1c.png)

**Comment by broofa** [comment]
> <strike>We will not help if you are rude.</strike>

# We will not help if you are rude.

FTFY.
