### ISSUE TITLE
Getting `TypeError: Stringified UUID is invalid` error 

### ISSUE THREAD

**Issue by RezaRahmati** [uuidjs/uuid#500]
## Describe the bug
I used uuid in Angular project and calling v4, when serving angular with `ng serve` option it works fine, when building angular for prod by `ng build --prod` or serving in prod mode by `ng serve --prod`, it throws  `TypeError: Stringified UUID is invalid` exception

## To Reproduce

1- create angular project
2- npm install uuid
3- call uuid v4 in component or service

## Expected behavior
Generate a guid

## Runtime

- OS: Windows, MacOs
- Runtime: Node 10, 
- Runtime Version: v8

## work around
Downgrading to v7.0.3 solved the issue

**Comment by ctavan** [comment]
Can you provide a minimum reproduction example (ideally as a separate GitHub repository)? The bug you are reporting sounds unexpected and should not definitely not happen. From the information you have provided so far it's difficult to tell if this is an actual problem of this library though.

**Comment by broofa** [comment]
Looking at `v4()` source, this error might occur if the calling code passes an `options.rng` or `options.random` resulting in invalid/incomplete set of random bytes.

Other than that, as @ctavan says, we'll need a [SSCCE](http://sscce.org/) that lets us reproduce the problem.

**Comment by sidpab** [comment]
TypeError: Stringified UUID is invalid
I am using package @azure/storage-blob which internally uses @azure/core-http which uses UUID. Everything was working fine until UUID latest version started breaking at
webpack:///./node_modules/@azure/core-http/node_modules/uuid/dist/esm-browser/stringify.js.pre-build-optimizer.js
I hope this info will help reproduce this issue. This issue only occur when build is done with --prod

**Comment by ctavan** [comment]
@sidpab when does this error occur? During the build process? Or when running the production build?

Can you provide a full [SSCCE](http://sscce.org/) that would allow us to reproduce this issue?

**Comment by sidpab** [comment]
build process works fine, this happens when application is running. I can reproduce this in local environment by command 
ng serve --prod
I am using below method from storage-blob which eventually fails with error above
blockBlobClient.uploadBrowserData({}..

**Comment by broofa** [comment]
@sidpab When we say "SSCCE", we mean something tangible we can use to reproduce the problem.  See also [this SO article](https://stackoverflow.com/help/minimal-reproducible-example).

Another option would be for you to diagnose the problem and explain exactly what's triggering this issue and why it's *our* problem (rather than, for example `@azure/core-http `'s issue). A good starting point for that would be to run your server with `--inspect-brk` and set a breakpoint [here](https://github.com/uuidjs/uuid/blob/master/src/stringify.js#L45) to see what's leading up to the exception.

**Comment by broofa** [comment]
Issue 508 (mentioned by ctavan, above) has a reproduceable case.  Looks like this is a result of Angular not properly transpiling the `uuid` module code.   Please continue any relevant conversation on that issue.

**Comment by ctavan** [comment]
@RezaRahmati @sidpab can you check if upgrading Angular works for you as well? https://github.com/uuidjs/uuid/issues/508#issuecomment-673677001

**Comment by RezaRahmati** [comment]
> @RezaRahmati @sidpab can you check if upgrading Angular works for you as well? [#508 (comment)](https://github.com/uuidjs/uuid/issues/508#issuecomment-673677001)

I was checking it on angular 9.1.9, didn't check on Angular 10, btw I downgrade uuid to 7.0.3 and it works

**Comment by ctavan** [comment]
For people coming here from Google: This is due to a bug in `@angular-devkit/build-angular@0.801.3`, it works with `@angular-devkit/build-angular@0.901.12` and later. See https://github.com/uuidjs/uuid/issues/508#issuecomment-677460598

**Comment by shahidql1** [comment]
With @angular-devkit under @angular7 caused the same issue on the production. But downgrading to uuid@v7.0.3 worked out.

**Comment by ctavan** [comment]
@shahidql1 as mentioned [in the comment right above](https://github.com/uuidjs/uuid/issues/500#issuecomment-677461059): This is a bug in Angular's production build minifier and seems to affect versions prior to `@angular-devkit/build-angular@0.901.12`.

**Comment by SherifNeamatalla** [comment]
Unfortunately I do not have the time right now to provide an example for this but I confirm that @angular-devkit/build-angular@~0.803.15 works, anything less than that doesn't. @ctavan  thanks dude you saved me lots of headache.

**Comment by Ruud-cb** [comment]
Hmm, but that would require to update to angular 9?
When I updated from 0.801.2 to 0.901.12.

I got an error when I try to run `ng serve`:

```
[error] Error: Job name "..getProjectMetadata" does not exist.
    at Observable.rxjs_1.Observable [as _subscribe] [projectPath]\ClientApp\node_modules\@angular-devkit\core\src\experimental\jobs\simple-scheduler.js:350:23)
    at Observable._trySubscribe [projectPath]\ClientApp\node_modules\@angular-devkit\core\node_modules\rxjs\internal\Observable.js:44:25)
    at Observable.subscribe [projectPath]\ClientApp\node_modules\@angular-devkit\core\node_modules\rxjs\internal\Observable.js:30:22)
    at C:\Users\Ruud\source\repos\CularBytesPlatform\CularBytes.Web.Portal\ClientApp\node_modules\@angular-devkit\core\node_modules\rxjs\internal\util\subscribeTo.js:22:31
    at Object.subscribeToResult [projectPath]\ClientApp\node_modules\@angular-devkit\core\node_modules\rxjs\internal\util\subscribeToResult.js:10:45)
    at SwitchMapSubscriber._innerSub [projectPath]\ClientApp\node_modules\@angular-devkit\core\node_modules\rxjs\internal\operators\switchMap.js:65:54)
    at SwitchMapSubscriber._next [projectPath]\ClientApp\node_modules\@angular-devkit\core\node_modules\rxjs\internal\operators\switchMap.js:55:14)
    at SwitchMapSubscriber.Subscriber.next [projectPath]\ClientApp\node_modules\@angular-devkit\core\node_modules\rxjs\internal\Subscriber.js:66:18)
    at SwitchMapSubscriber.notifyNext [projectPath]\ClientApp\node_modules\@angular-devkit\core\node_modules\rxjs\internal\operators\switchMap.js:86:26)
    at InnerSubscriber._next [projectPath]\ClientApp\node_modules\@angular-devkit\core\node_modules\rxjs\internal\InnerSubscriber.js:28:21)
    at InnerSubscriber.Subscriber.next [projectPath]\ClientApp\node_modules\@angular-devkit\core\node_modules\rxjs\internal\Subscriber.js:66:18)
    at C:\Users\Ruud\source\repos\CularBytesPlatform\CularBytes.Web.Portal\ClientApp\node_modules\@angular-devkit\core\node_modules\rxjs\internal\util\subscribeTo.js:17:28
    at Object.subscribeToResult [projectPath]\ClientApp\node_modules\@angular-devkit\core\node_modules\rxjs\internal\util\subscribeToResult.js:10:45)
    at SwitchMapSubscriber._innerSub [projectPath]\ClientApp\node_modules\@angular-devkit\core\node_modules\rxjs\internal\operators\switchMap.js:65:54)
    at SwitchMapSubscriber._next [projectPath]\ClientApp\node_modules\@angular-devkit\core\node_modules\rxjs\internal\operators\switchMap.js:55:14)
    at SwitchMapSubscriber.Subscriber.next [projectPath]\ClientApp\node_modules\@angular-devkit\core\node_modules\rxjs\internal\Subscriber.js:66:18)
```

Most likely due only updating that library and not the rest (although it adds a lot of other packages underneath.
