### ISSUE TITLE
TypeScript types don't match the current version

### ISSUE THREAD

**Issue by goloroden** [uuidjs/uuid#502]
## Describe the bug

The bug is pretty simple – the TypeScript types of this module (`@types/uuid`) don't match the current version of `uuid` (right now, 8.3.0). Eg., the `validate` function and `NIL` are unknown. Hence it's not possible to use `uuid` 8.3.0 with these functions in a TypeScript project, unless you tell the compiler to ignore errors. It would be great to have updated types 😊

## How to reproduce

- [ ] Create a TypeScript project
- [ ] Install `uuid@8.3.0` and `@types/uuid@8.0.0``
- [ ] Import the `validate` function or the `NIL` property into your code
- [ ] Try to compile

## Expected behavior

The project should compile.

## Runtime

Is not relevant for this issue, as it is not runtime-specific.

**Comment by ctavan** [comment]
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/46395

**Comment by mwgamble** [comment]
Looks like an updated version of `@types/uuid` landed a few hours ago.

**Comment by goloroden** [comment]
Yes, and it includes a definition for validate, but not for NIL. So this issue is still open.

**Comment by ctavan** [comment]
Yes, we are still waiting for https://github.com/DefinitelyTyped/DefinitelyTyped/pull/46395

**Comment by ctavan** [comment]
`@types/uuid@8.3.0` has finally been published. Feel free to reopen if it doesn't meet your needs!
