### ISSUE TITLE
Error: Unable to resolve module `./bytesToUuid.js` from `node_modules\uuid\dist\v1.js`

### ISSUE THREAD

**Issue by imsam67** [uuidjs/uuid#505]
In my React Native app, I upgraded the uuid package from 8.2.0 to 8.3.0 and now I keep getting this error and my app doesn't build anymore.

Here's the screen shot of what I'm seeing:
![Annotation 2020-08-04 220431](https://user-images.githubusercontent.com/15844030/89370847-ee55d200-d69e-11ea-8c07-e396c2457239.png)

Any idea what's going on here?

BTW, I'm on Windows 10 and the version of Node is 14.1.0. React Native version is 0.63.1

**Comment by ctavan** [comment]
This looks like an issue with either your react-native cache or your local `node_modules` directory. Have you tried cleaning and reinstalling/rebuilding both? The latest version of `uuid` does not require `bytesToUuid.js` from `v1.js`, see https://unpkg.com/browse/uuid@8.3.0/dist/v1.js

So there must be some leftovers in you local setup from earlier versions of `uuid`.

**Comment by imsam67** [comment]
Clearing the project cache fixed the issue. Thank you!
