### ISSUE TITLE
Support for ESM. Modules are not concatenated

### ISSUE THREAD

**Issue by o-alexandrov** [uuidjs/uuid#507]
## Is your feature request related to a problem? Please describe.

The [wrapper ESM approach](https://github.com/uuidjs/uuid/pull/423) doesn't produce the most optimal bundles.

## Describe the solution you'd like

It'd be better, if this pkg was built using rollup for the most efficient builds for every environment.
- shipped with built-in TypeScript & written using latest ES

## Additional context

In the following example, `uuid` is "annoyingly" a single module that is not concatenated by [webpack](https://webpack.js.org/plugins/module-concatenation-plugin/).
<img width="1792" alt="Screen Shot 2020-08-13 at 3 57 21 AM" src="https://user-images.githubusercontent.com/9992724/90115895-58fbb300-dd1a-11ea-987d-4db6db4b5588.png">

**Comment by ctavan** [comment]
How exactly are you building your bundle? This package is built in a way that webpack and rollup _should_ pick up optimized ESM  builds that allow for tree-shaking.

Could you provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) for how you got to the bundle shown above?

Also the module _is_ written in ESModule syntax for precisely the reasons of tree-shakeability and we don't include the TypeScript types on purpose, see https://github.com/uuidjs/uuid/issues/368#issuecomment-587330334.

**Comment by o-alexandrov** [comment]
oups, I apologize, it was improper dependencies hoisting, that uuid on the graph above is `3.4.0`
