### ISSUE TITLE
Could not find a declaration file for module 'uuid'.

### ISSUE THREAD

**Issue by rahadkc** [uuidjs/uuid#519]
Try:
`npm i uuid`
`npm i @types/uuid`

Then:
`import { v4 as uuid4 } from 'uuid'` 

Getting this error in console:

<img width="837" alt="Screenshot 2020-09-19 at 9 45 28 PM" src="https://user-images.githubusercontent.com/8745638/93671035-909c0e80-fac1-11ea-911c-737dffd239de.png">

Thanks

**Comment by ctavan** [comment]
Your ticket doesn’t provide all the required information.

Please open a new bug report and make sure to fill out the entire bug report template.

**Comment by fnagel** [comment]
Same issue here. @rahadkc take a look here: https://github.com/DefinitelyTyped/DefinitelyTyped/issues/42634

**Comment by kvk30** [comment]
How to install it in the bun package module?
