### ISSUE TITLE
validate REGEX incorrect?

### ISSUE THREAD

**Issue by ionTea** [uuidjs/uuid#521]
## Describe the bug
With the validation introduced in https://github.com/uuidjs/uuid/commit/0e6c10ba1bf9517796ff23c052fc0468eedfd5f4 causes the namespace we use for `v5` is no longer deemed to be valid. However, the namespace UUID seems to be a valid: `efca7b02-deaf-dead-d3de-c0ffeec0ffee`

The regex used to verify the UUID is: 
```
^(?:[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}|00000000-0000-0000-0000-000000000000)$
```

I'm not sure this regex is correct.

## How to reproduce

```
const { v5 } = require("uuid");

const res = v5("this should work", "efca7b02-deaf-dead-d3de-c0ffeec0ffee");
```

results in:
```
/uuid-test/node_modules/uuid/dist/parse.js:14
    throw TypeError('Invalid UUID');
    ^

TypeError: Invalid UUID
    at parse (/uuid-test/node_modules/uuid/dist/parse.js:14:11)
    at generateUUID (/uuid-test/node_modules/uuid/dist/v35.js:39:38)
```

## Expected behavior

[Clear, concise description of what you expected]

It should allow a valid UUID to be used as a namespace.

## Runtime

- OS: macOS
- Runtime: Node.js
- Runtime Version: v14.7.0

## Additional information

**Comment by ctavan** [comment]
I'm afraid but `efca7b02-deaf-dead-d3de-c0ffeec0ffee` is certainly not an RFC-compliant UUID. As you can see from the regex, the first character after the second `-` is the UUID version, which must be one of `1345` and the first character after the third dash must be one of `89ab`.

However your UUID was generated in the first place, it is not something that is covered by [RFC4122](https://www.ietf.org/rfc/rfc4122.txt)

That said, a workaround that currently exists has been described in: https://github.com/uuidjs/uuid/issues/511#issuecomment-677913838

However please don't assume that this workaround will work forever. We are exploring changes to the current behavior in https://github.com/uuidjs/uuid/issues/512 so feel free to chime in there as well.

**Comment by ionTea** [comment]
Alright, thanks for linking that other issue! I'll close this one 👍
