### ISSUE TITLE
Error "Cannot read property 'getRandomBase64' of undefined" , when running test file

### ISSUE THREAD

**Issue by gandarain** [uuidjs/uuid#522]
## Describe the bug

I try to use uuid and react native random values on react native my project. Everything is working fine, but when I run my test file, I get an error 'Cannot read property 'getRandomBase64' of undefined'. 

## How to reproduce

**REQUIRED**: Provide a [Minimal, Complete, and Verifiable](https://stackoverflow.com/help/minimal-reproducible-example) example so that we (the `uuid` maintainers) can reproduce the problem. Issues that do not provide this will be closed without investigation.

## Expected behavior

That error gone.

## Runtime

- OS: [macOS]
- Runtime: [react-native]
- Runtime Version: [e.g. 0.63.2]

## Additional information

![Screen Shot 2020-10-02 at 10 37 22](https://user-images.githubusercontent.com/27923352/94902959-376dab00-04c3-11eb-98ef-6dca632c93fc.png)

**Comment by ctavan** [comment]
![image](https://user-images.githubusercontent.com/508118/94905692-93253d80-049d-11eb-8dde-fc47cd51347a.png)
