### ISSUE TITLE
allow to specify a uuid version to `validate` method

### ISSUE THREAD

**Issue by ben8p** [uuidjs/uuid#526]
## Is your feature request related to a problem? Please describe.

Cross referencing https://github.com/thenativeweb/uuidv4/issues/221

There is currently no way to know if a given string is a valid uuid of a specific version.  We can only know if it is a valid uuid (regardless of the version)

## Describe the solution you'd like

add a 2nd argument to `validate` where we can specify the version of the uuid to check against.

## Describe alternatives you've considered

add methods such as `validateV4`, `validateV5`, ....

## Additional context

See the uuidv4 issue linked on top of the feature request

**Comment by ctavan** [comment]
You can use [`uuid.version()`](https://github.com/uuidjs/uuid#uuidversionstr), which calls validate under the hood and returns the version as a number. It throws the same error as [`uuid.validate()`](https://github.com/uuidjs/uuid#uuidvalidatestr) when call with a malformed uuid.

Does that work for you?

**Comment by ctavan** [comment]
If you don't want to catch the error you can also do something like:

```js
function validateV4(str) {
  return uuid.validate(str) && uuid.version(str) === 4;
}
```

**Comment by ben8p** [comment]
Sounds great!
Indeed using`.version` is a satisfying approach.

Thanks
Closing for now.
