### ISSUE TITLE
Typescript project: TypeError: uuid_1.validate is not a function

### ISSUE THREAD

**Issue by adamjakab** [uuidjs/uuid#528]
## Describe the bug
I am using this library in a typescript project. I have the v4 generator function working correctly but when I call the `validate` or `version` methods I get the following error: 
`TypeError: uuid_1.validate is not a function`

This happens when I run my jest test on an [extremely simple code](https://github.com/adamjakab/CF-Worker-Tests/blob/0e85eb7754c3e4e7168a4ecbc50217bb2aba8082/src/repository/repository.ts#L31).

## Runtime

- OS: macOS
- Runtime: jest
- Runtime Version: 24.9.0

**Comment by broofa** [comment]
Due to [using an old version](https://github.com/adamjakab/CF-Worker-Tests/blob/0e85eb7754c3e4e7168a4ecbc50217bb2aba8082/package.json#L52)?

As [noted in the docs](https://github.com/uuidjs/uuid#api-summary), `validate()` was not introduced until v8.3.

**Comment by adamjakab** [comment]
Good catch! I don't know why this happens (and I retried even after force cleaning npm cache) but when I issue `npm install uuid` I get version 3.3.3 installed. I had to install it declaring the version number explicitly by `npm install uuid@8.3.1`. Everything is running smoothly now, thanks.

**Comment by rendall** [comment]
This happened to me, too. Strange that yarn didn't install the latest version
