### ISSUE TITLE
Unable to resolve module `uuid/v4`

### ISSUE THREAD

**Issue by JakyChen** [uuidjs/uuid#533]
## Describe the bug

Hi, I am using React Native to run uuid but come across this error:

error: bundling failed: Error: Unable to resolve module `uuid/v4` from `src/actions/TeamActions.js`: uuid/v4 could not be found within the project.

## How to reproduce

npm install react-native-get-random-values
npm install uuid

import 'react-native-get-random-values';
import { v4 as uuidv4 } from 'uuid'

const uuid = uuidv4()

## Expected behavior

To generate a random uuid for my project

## Runtime

OS: MacOS
Runtime: Node.JS
Runtime version: v15.2.1 and v10.14.0
React-Native version: 0.61.4
uuid version: ^8.3.1

## Additional information
What I've tried so far:
- Deleting and reinstalling dependencies in node_modules
- Clearing watchman cache
- Clearing all temporary files for node
- Upgrading node to the latest version

**Comment by nylon22** [comment]
@JakyChen i'm running into this issue as well. how were you able to resolve it?

**Comment by TrySound** [comment]
The error happens because one of your dependencies forgot to list uuid or listed range as "*".

**Comment by JakyChen** [comment]
> @JakyChen i'm running into this issue as well. how were you able to resolve it?

I realized a previous developer imported uuid as `import uuidv4 from 'uuid/v4'` and caused this error.
Just make sure you correct all your imports to the same code as written above `import { v4 as uuidv4 } from 'uuid'` and that your uuid package is updated to the latest version. It should be good after that!
