### ISSUE TITLE
Please port getLeastSignificantBits() and getMostSignificantBits() from java

### ISSUE THREAD

**Issue by tinjaw** [uuidjs/uuid#535]
See https://stackoverflow.com/questions/64917603/looking-for-javascript-equivalents-for-javas-getleastsignificantbits-and-getm

I am interfacing with an API that requires the UUID to be packaged as two 64-bit integers as computed by those functions.

**Comment by broofa** [comment]
IMHO, this is out of scope for this project.   JavaScript doesn't have a true 64-bit integer data type (JS Numbers are 64-bit floats per IEEE822) and the incremental value in this is pretty small given that `parse.uuid()` is already a thing.

FWIW, I believe you can roll your own version of these functions using `uuid.parse()`.  E.g. ...

```
// First 64 bits => BigInt
uuid.parse(id).slice(0,8).reduce((a, b) => a << 8n | BigInt(b), 0n).toString(16)

// Last 64 bits => BigInt
uuid.parse(id).slice(8, 16).reduce((a, b) => a << 8n | BigInt(b), 0n).toString(16)
```
