### ISSUE TITLE
uuid.parse is not importing properly

### ISSUE THREAD

**Issue by tinjaw** [uuidjs/uuid#541]
This not a bug report. This is a request for help finding help.

In general, where can I get help using uuid? I don't see any forums or Discord listed.

If this is the appropriate place, below are the first 24, or so, lines of my file. I am importing `uuid.parse`, but it is not importing properly.

```
import { remote } from 'electron';
import { promises } from 'fs';
import jsonata from 'jsonata';
import sha1 from 'sha1';
import { v4 as uuidv4, parse as uuidParse } from 'uuid';

const xslx = require('json-as-xlsx');
const { create } = require('xmlbuilder2');
const dF = require('../date.format');

function getMostSignificantBits(id) {
  // First 64 bits => BigInt
  console.log(uuidv4); // returns as expected
  console.log(uuidParse); // returns undefined
  return uuidParse(id)
    .slice(0, 8)
    .reduce((a, b) => (a << 8n) | BigInt(b), 0n);
}

function getLeastSignificantBits(id) {
  // Last 64 bits => BigInt
  return uuidParse(id)
    .slice(8, 16)
    .reduce((a, b) => (a << 8n) | BigInt(b), 0n);
}
```

from yarn.lock

```
...
"@types/uuid@^8.3.0":
  version "8.3.0"
  resolved "https://registry.yarnpkg.com/@types/uuid/-/uuid-8.3.0.tgz#215c231dff736d5ba92410e6d602050cce7e273f"
  integrity sha512-eQ9qFW/fhfGJF8WKHGEHZEyVWfZxrT+6CLIJGBcZPfxUh/+BnEj+UCGYMlr9qZuX/2AltsvwrGqp0LhEW8D0zQ==
...
uuid@^8.3.1:
  version "8.3.1"
  resolved "https://registry.yarnpkg.com/uuid/-/uuid-8.3.1.tgz#2ba2e6ca000da60fce5a196954ab241131e05a31"
  integrity sha512-FOmRr+FmWEIG8uhZv6C2bTgEVXsHk08kE7mPlrBbEe+c3r9pjceVPgupIfNIhc4yx55H69OXANrUaSuu9eInKg==
```

**Comment by TrySound** [comment]
Please check `your_project_dir/node_modules/uuid/package.json`

**Comment by tinjaw** [comment]
https://pastebin.com/r49DdN4B

What am I looking for in that file?

**Comment by TrySound** [comment]
All look good. Weird. Could you make a repro example?

**Comment by tinjaw** [comment]
@TrySound The project won't really be executable for you. And if it does run, you won't have the necessary data files. But I think I can at least push the project to a public repo long enough for you, or anyone, to take a look at it to help me out.

Let me enjoy the weekend making music. I will get back to code/work Monday and post the repo. Thanks.

**Comment by ctavan** [comment]
You could try downloading https://github.com/uuidjs/uuid/blob/master/examples/node-esmodules/example.mjs and executing it (`node example.mjs`) and see if this works?

**Comment by ctavan** [comment]
This issue is missing a reproduction case so unfortunately it's not actionable for us.

Is this still a problem? If so, please try to provide a [Minimal, Complete, and Verifiable](https://stackoverflow.com/help/minimal-reproducible-example) example and reopen this bug.
