### ISSUE TITLE
@8.x.x: Package subpath './dist/index.js' is not defined by "exports"

### ISSUE THREAD

**Issue by juuyan** [uuidjs/uuid#550]
## Describe the bug

Use uuid 8.x.x in:
- Lambda
- node.js 12

infrastructure is created and deployed by [pulumi](https://www.pulumi.com/) 

Get the following err:
```
{
    "errorType": "Error",
    "errorMessage": "Package subpath './dist/index.js' is not defined by \"exports\" in /var/task/node_modules/uuid/package.json",
    "code": "ERR_PACKAGE_PATH_NOT_EXPORTED",
    "stack": [
        "Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './dist/index.js' is not defined by \"exports\" in /var/task/node_modules/uuid/package.json",
        "    at throwExportsNotFound (internal/modules/esm/resolve.js:285:9)",
        "    at packageExportsResolve (internal/modules/esm/resolve.js:508:3)",
        "    at resolveExports (internal/modules/cjs/loader.js:424:36)",
        "    at Function.Module._findPath (internal/modules/cjs/loader.js:464:31)",
        "    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:802:27)",
        "    at Function.Module._load (internal/modules/cjs/loader.js:667:27)",
        "    at Module.require (internal/modules/cjs/loader.js:887:19)",
        "    at require (internal/modules/cjs/helpers.js:74:18)",
        "    at /var/task/__index.js:81:37",
        "    at Runtime.__f0 [as handler] (/var/task/__index.js:114:6)"
    ]
}
```

While in 3.x.x and 7.x.x, things work properly.

## How to reproduce

- clone a simple pulumi sample for lambdan & api-gatway
- use uuid in lambda function.
- Deploy and call the api

## Runtime

node.js 12

**Comment by ctavan** [comment]
The issue template clearly states:

**REQUIRED**: Provide a [Minimal, Complete, and Verifiable](https://stackoverflow.com/help/minimal-reproducible-example) example so that we (the `uuid` maintainers) can reproduce the problem. Issues that do not provide this will be closed without investigation.

Please follow the issue template as we can otherwise not provide you with platform-specific support.

**Comment by marksmithson** [comment]
For reference:

This is due pulumi code generation when uuid is used within a serialised function. Pulumi captures references used in the code being serialised and uses require.cache to resolve the path.

This results in the following being generated `require("uuid/dist/index.js")` which is not allowed in 8.x.x.

Allowing `./dist/index.js` in the package.json would prevent this error. However I am not convinced that this is the right approach here.

A workaround is to use require within the function, or to wrap uuid in another module that pulumi can require properly.
