### ISSUE TITLE
The validate function is not recognizing 91165781-785f-44bd-5117-08d8bb99840c

### ISSUE THREAD

**Issue by farhadnowzari** [uuidjs/uuid#552]
Hi, I have the uuid package in my project and I'm importing the validate function into the project and I just want to validate my strings to be UUID and I do not care about the version.
It works fine with:
```
59c846ae-f0b7-48d4-893c-08d881833bec
e1923818-b0e9-4581-9054-08d8b1566964
```
but it doesn't validate:
```
91165781-785f-44bd-5117-08d8bb99840c
```

I'm running this in vue and in development environment which I think does not matter

**Comment by TrySound** [comment]
See https://github.com/uuidjs/uuid/issues/521

**Comment by broofa** [comment]
> 91165781-785f-44bd-5117-08d8bb99840c is not valid uuid.

Specifically, the `5` in `5117`,  means the `variant` field is invalid.  It should be one of `8`, `9`, `a`, or `b`.
