### ISSUE TITLE
Android app crashes on start in react native (ejected expo project)

### ISSUE THREAD

**Issue by eliottguillaumin** [uuidjs/uuid#557]
## Describe the bug

After installing the library the android app will crash on start without any error.

## How to reproduce

Create a project on Expo SDK 40, eject the project from expo to bare workflow.
Install the react-native-get-random-values library with NPM then install the UUID library using the provided instructions.
You can then try running npm run android for the bug to show.

## Expected behavior

Android app starts normally

## Actual behavior

Android app crashes on start with no error

## Runtime

- OS: macOS Catalina
- Runtime: Expo SDK 40 Bare Workflow / react-native
- Runtime Version: [e.g. 14.2.0]

**Comment by eliottguillaumin** [comment]
To resolve this issue make sure you run the following after installing (should be added to the intallation page):
`react-native link react-native-get-random-values`
or if you are using an ejected expo app:
`npx react-native link react-native-get-random-values`

**Comment by ctavan** [comment]
@eliottguillaumin if this is necessary, it should be added to the readme at https://github.com/LinusU/react-native-get-random-values#readme

Would you mind opening an issue over there?

**Comment by eliottguillaumin** [comment]
I will when I get the time thank you

Téléchargez Outlook pour Android<https://aka.ms/ghei36>
________________________________
