### ISSUE TITLE
crypto__default.default.randomFillSync is not a function

### ISSUE THREAD

**Issue by milobluebell** [uuidjs/uuid#558]
## Describe the bug

`show error message: Uncaught TypeError: crypto__default.default.randomFillSync is not a function built by rollup`

## How to reproduce

npm install uuid, and build a project by rollup without even though specified a global config

## Expected behavior

`show error message: Uncaught TypeError: crypto__default.default.randomFillSync is not a function built by rollup`

## Runtime

- OS: macOS
- Runtime: Node.js, Chrome
- Runtime Version: 14.12.0 

## Additional information

where is the crypto dependency defined (included in rng.js line.1 ) in this project?

**Comment by TrySound** [comment]
Do you run the code in bowser?

**Comment by TrySound** [comment]
See https://github.com/rollup/plugins/tree/master/packages/node-resolve#browser

**Comment by milobluebell** [comment]
> Do you run the code in bowser?

yup

**Comment by TrySound** [comment]
Then you need to bundle for browser. By default rollup/plugin-node-resolve resolves node versions. See the option in link above.

**Comment by milobluebell** [comment]
> See https://github.com/rollup/plugins/tree/master/packages/node-resolve#browser

it worked successfully, ty!😊
