### ISSUE TITLE
Default import is not working in typescript

### ISSUE THREAD

**Issue by tbhaxor** [uuidjs/uuid#562]
## Describe the bug

UUID has not been working in my typescript project but is working in node.js

## How to reproduce

![image](https://user-images.githubusercontent.com/28386721/109727934-445e0a00-7bdb-11eb-89a7-3064b693b743.png)

![image](https://user-images.githubusercontent.com/28386721/109727995-622b6f00-7bdb-11eb-8e67-4e33714ddf4a.png)

## Expected behavior

Default export is messed up, need to be fixed. After that it should work like in nodejs

## Runtime

- OS: Linux
- Runtime: Node.js, Typescript
- Runtime Version: v15, v4.2.2

## Additional information

![image](https://user-images.githubusercontent.com/28386721/109728170-b1719f80-7bdb-11eb-9159-823b80d6b421.png)

**Comment by TrySound** [comment]
There is not default export in uuid package. Commonjs does not have nor default export nor named exports. It has only `module.exports` reference.
See example https://github.com/uuidjs/uuid#quickstart
