### ISSUE TITLE
`npm deprecate` versions prior to v7?

### ISSUE THREAD

**Issue by broofa** [uuidjs/uuid#572]
[This comment](
https://github.com/uuidjs/uuid/issues/531#issuecomment-831826683) has me thinking we should do this:
```
npm deprecate uuid<7 "Pre-v7 versions of this library may use Math.random() \
in certain circumstances, which is known to be problematic.  Please upgrade to a \
more recent version.  See https://v8.dev/blog/math-random for details."
```

**Comment by ctavan** [comment]
I don’t know exactly what consequences this will have. But in principle this sounds very good to me!

**Comment by LinusU** [comment]
I think the only consequence would be a warning printed when running `npm install`?

I'm all for this 👍

**Comment by broofa** [comment]
Done.  For the record, here's the command I ran:
```
npm deprecate uuid@"<7" "Please upgrade `uuid` to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details."
```

![image](https://user-images.githubusercontent.com/164050/120001594-a7a7d000-bf6f-11eb-8d44-0c8465942305.png)
