### ISSUE TITLE
Generate UUIDs starting with a letter

### ISSUE THREAD

**Issue by Hacklog24** [uuidjs/uuid#577]
## Is your feature request related to a problem? Please describe.

Hello,
for specific needs, would it be possible to generate UUIDs with at least one letter at the start?

## Describe the solution you'd like
For example:
1 ) e1b86008-fef5-41e8-9c14-f817e1a5fd45
2) a2b84546-f443-4515-89d2-593d6e1e448d
3) ffd718f7-14ae-431f-b1c1-59c572f6ebba
and so on...

## Additional context

I'm using the uuidv4() function;

Thank you so much for your support!

**Comment by ctavan** [comment]
This library generates UUIDs according to [RFC 4122](https://www.ietf.org/rfc/rfc4122.txt).

UUID v4 are random, so there is no control over how they start. If this is a requirement, then UUIDs may not be the right choice for your use case.
