### ISSUE TITLE
Maintainers should not be able to commit directly to `master`

### ISSUE THREAD

**Issue by broofa** [uuidjs/uuid#590]
I accidentally committed to master [here](https://github.com/uuidjs/uuid/issues/586#ref-commit-67a5bc5).  That sort of thing shouldn't be doable.  `master` commits should only be the result of merging an approved PR.

**Comment by broofa** [comment]
FWIW, I just renamed `master` to `main`.  It mostly seems to be working. :-)

**Comment by ctavan** [comment]
I think we should be ready to enable branch protection for admins on `main` once we have #636 in place as we'll no longer need the commits that `npm run release` currently creates on `main` directly.
