### ISSUE TITLE
Duplicate uuids from a specific user-agent

### ISSUE THREAD

**Issue by tufandevrim** [uuidjs/uuid#595]
## Describe the bug

We are seeing duplicate uuids (generated by uuidv4 function) are coming from only this user agent: `Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:78.0) Gecko/20100101 Firefox/78.0`. The instrumentation payload are coming from different users from different locations but they are sending same uuids with this user-agent. Has anyone ever experienced the similar issue before?

I don't think this is a bug in uuid, could be a bug in this specific browser version but just wanted to see if anyone had a similar issues before.

**Comment by ctavan** [comment]
Please see https://github.com/uuidjs/uuid/issues/546

If your site is publicly available to the internet, your are most likely seeing search engine crawler traffic which often has deterministic random number generators.
