### ISSUE TITLE
Secure Contexts

### ISSUE THREAD

**Issue by ctavan** [uuidjs/uuid#602]
Now that #600 has been merged, I just realized that given https://github.com/WICG/uuid/issues/23 this change may actually have introduced a subtle breaking change in that in modern browsers v4 UUID generation will now only work in secure contexts.

How are we going to deal with this? (cc @LinusU)

**Comment by LinusU** [comment]
I believe that `crypto.randomUUID` will simply be undefined in unsecure contexts, and then we'll fall back to the standard implementation:

<img width="798" alt="image" src="https://user-images.githubusercontent.com/189580/144402610-bb7634cb-a203-427e-9c4a-5b07159f0225.png">

<img width="662" alt="image" src="https://user-images.githubusercontent.com/189580/144402803-5df41caa-20bf-48aa-8bd0-54ba1d242024.png">

**Comment by ctavan** [comment]
OK, that's a good observation. I guess for the purpose of this library, which always tries to use the best-available resource for generating randomness, the observed behavior is fine.

I'm wondering what code paths our (browser) tests are testing though… I think we should investigate if they are loading the test page in a secure or insecure context (if we want to ensure that the native code path is covered).

**Comment by LinusU** [comment]
> I think we should investigate if they are loading the test page in a secure or insecure context (if we want to ensure that the native code path is covered).

Very good point 👍

**Comment by broofa** [comment]
FWIW, 'looks like BrowserStack tests use HTTP:
![CleanShot 2021-12-02 at 08 44 42@2x](https://user-images.githubusercontent.com/164050/144465614-23611856-70ea-4773-93c7-257b4cfc361c.png)

**Comment by ctavan** [comment]
As far as I understand, APIs restricted to secure contexts are still available on localhost… But still have to verify.

**Comment by ctavan** [comment]
I tried Browserstack live local testing with Chrome 95 and it indeed appears like `crypto.randomUUID` _is_ available on `127.0.0.1:9000`: 

![image](https://user-images.githubusercontent.com/508118/144514401-003f1b3d-dd06-48ac-ac95-b6dedca40c81.png)


@bcoe does this match your expectations as well?

**Comment by broofa** [comment]
From[ §3.1.5](https://w3c.github.io/webappsec-secure-contexts/#is-origin-trustworthy)  of the Secure Context spec:

> If the user agent conforms to the name resolution rules in [let-localhost-be-localhost] and one of the following is true:
> * origin’s host is "localhost" or "localhost."
> * origin’s host ends with ".localhost" or ".localhost."
> 
> then return "Potentially Trustworthy".

**Comment by broofa** [comment]
@ctavan Do you know if there's a way to configure our BrowserStack CI to use a non-localhost domain for testing? (like... add `127.0.0.1 test.com` to "/etc/hosts", or use some pre-configured domain alias they might supply?)

**Comment by ctavan** [comment]
I haven’t investigated yet but I agree that we should try to establish test coverage for this case.

**Comment by broofa** [comment]
It looks like browserstack serves a DNS entry for `bs-local.com` that maps to `127.0.0.1`. ([source](https://www.browserstack.com/question/39574)).  In theory we could use that.  However adding `hostname: 'bs-local.com'` to wdio.conf.js breaks the browserstack environment.

```
$ dig bs-local.com

; <<>> DiG 9.10.6 <<>> bs-local.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 5526
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 8192
;; QUESTION SECTION:
;bs-local.com.			IN	A

;; ANSWER SECTION:
bs-local.com.		300	IN	A	127.0.0.1

;; Query time: 50 msec
;; SERVER: 172.20.0.1#53(172.20.0.1)
;; WHEN: Sun May 15 08:02:35 PDT 2022
;; MSG SIZE  rcvd: 57
```

**Comment by broofa** [comment]
While I'd love to get insecure context testing in CI, I don't see a trivial path to that at the moment. Nor am I concerned enough to say this should hold up the v9 release.  We can revisit if/when we miss a regression in a future release.  I have every confidence our users will complain loudly when that happens.  😈 

@ctavan If you feel this needs to be a v9 release blocker go ahead and reopen.
