### ISSUE TITLE
TypeError: undefined is not an object (evaluating 'rnds[6]')

### ISSUE THREAD

**Issue by MennatAllahMagdy** [uuidjs/uuid#614]
## Describe the bug

When I use v4 from uuid, I got that error 'TypeError: undefined is not an object (evaluating 'rnds[6]')'

## How to reproduce

import { v4 as uuidv4 } from 'uuid';
const Uid = uuidv4();

## Runtime

- OS: [WSL2]
- "react-native": "0.64.3"
- "uuid": "^8.3.2"
- "@types/uuid": "^8.3.2"

**Comment by nianxi** [comment]
Same issue with you.
Working online but collects errors everyday:
TypeError: Cannot read property '6' of undefined

**Comment by broofa** [comment]
@nianxi : Can you provide complete instructions for how to reproduce this?

**Comment by stefreak** [comment]
For me, this works when "Debug with Chrome" in my expo app is enabled, and when "Debug with Chrome" is disabled I get the error. Using expo and running the app in iOS Simulator

**Comment by stefreak** [comment]
Update: For me, the issue seems to be gone after installing `react-native-get-random-values`.
