### ISSUE TITLE
node@16.14 import assertions break examples/node-esmodules/example.mjs test

### ISSUE THREAD

**Issue by broofa** [uuidjs/uuid#619]
@ctavan:

* https://github.com/nodejs/node/pull/41736 has landed, causing our 16.x CI test to break.
* There's a [simple fix](https://github.com/uuidjs/uuid/pull/618/commits/ed72e5aea59e7e354a8ed727839fd376527ca100), but this won't build on older node versions due to the unexpected syntax.
* My temporary fix for #618 is to lock our CI test to node@16.13, but that's just a band-aid.  We should be testing on the latest major version across the board.
* An alternative is to just remove that import and not use it.  But it might be testing an [important feature](https://github.com/uuidjs/uuid/blob/main/examples/node-esmodules/example.mjs#L69-L70), so I'm hesitant to do that.

Care to comment (or, better, fix)?

**Comment by ctavan** [comment]
First of all it took me a while to realize that the unflagging of `--experimental-json-modules` (https://github.com/nodejs/node/pull/41736) has in fact not yet made it to the 16.x line of Node.js.

The problematic piece seems to be the import assertions that were [added in 16.14.0](https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V16.md#2022-02-08-version-16140-gallium-lts-danielleadams).

In any case, the best thing I could come up with was extracting the `package.json` edge case into a separate test that is only run on node 16.x.

I would like to keep coverage of this edge case as it was a real world problem that we once fixed. At the same time I would like to keep esm tests running on Node.js 14 which also have stable support for them.
