### ISSUE TITLE
What is the reasoning to limit to 10000 uuid per second? There are 1e+9 nanaseconds in one second right ?

### ISSUE THREAD

**Issue by RatchapongT** [uuidjs/uuid#628]
https://github.com/uuidjs/uuid/blob/7ce4e9aaf51ffde8bc7c08fd356e44cfc685573e/src/v1.js#L74

**Comment by broofa** [comment]
> limit to 10000 uuid per ~~second~~ millisecond

FTFY.  `nsecs` nominally tracks the timestamp offset from the current `msecs` time, in 100-nanosecond intervals.  I.e. it's the limit per millisecond... or 10,000,000/second.

See also [RFC §2, Motivation](https://datatracker.ietf.org/doc/html/rfc4122#section-2): _"The UUID generation algorithm described here supports very high allocation rates of up to 10 million per second per machine"_
