### ISSUE TITLE
[BUG] condition sentence is always true in rng.js

### ISSUE THREAD

**Issue by fyzhu** [uuidjs/uuid#649]
### Before you begin...

- [X] I have searched the existing issues
- [X] I am not using version 13.x of node  (if so, please upgrade)

### Description of the problem

<img width="541" alt="image" src="https://user-images.githubusercontent.com/5175751/184593463-09bbbcce-7331-4684-bff9-19244a9b39e6.png">

**Comment by ctavan** [comment]
`poolPtr` is set to `0` after pool population https://github.com/uuidjs/uuid/blob/1110ae66cc7602793619b51047b59affba93d19a/src/rng.js#L9

and incremented with every invocation of the `rng()` here https://github.com/uuidjs/uuid/blob/1110ae66cc7602793619b51047b59affba93d19a/src/rng.js#L11

Therefore the expression does NOT always evaluate to true.
