### ISSUE TITLE
Add info about `@types/uuid`

### ISSUE THREAD

**Issue by Snailedlt** [uuidjs/uuid#666]
### Feature description

Like the title said, add info about `@types/uuid` for TypeScript users. 

## Why?

I was about to submit a bug report because I got this error: `Uncaught ReferenceError: require$$0 is not defined`.

I wasn't able to reproduce the issue though, so I ended up almost giving up. Then I stumbled upon a [comment](https://dev.to/galkin/crypto-randomuuid-vs-uuid-v4-47i5#comment-21l5g) mentioning `@types/uuid`. I gave it a try, and sure enough it worked, and fixed the error.

I find it quite odd that `@types/uuid` isn't mentioned anywhere, given how popular TypeScript is, and the error that occurred when I used the library without installing the types.

## How?
Just add `npm i -D @types/uuid` to the documentation
```sh
npm i uuid
npm i -D @types/uuid #TypeScript types
```

### Additional information

Typescript has become so popular that including the types by default should be seriously considered. Quite a few libraries have done this already, though I can't remember any off the top of my head.

**Comment by broofa** [comment]
> Uncaught ReferenceError: require$$0 is not defined.

95% sure this error is unrelated to `@types/uuid`.

> I find it quite odd that @types/uuid isn't mentioned anywhere

VSCode and `tsc`   are quite vocal about modules that don't have type declarations, and also quite specific in what to do about that.   The use of `@types/...` is well-documented and well understood.

I.e. This isn't an issue specific to this project, and dealing with issues of this sort are (imho) out of scope of the README.  If one of the other maintainers feels differently, they're welcome to re-open.

![CleanShot 2022-12-09 at 09 24 40@2x](https://user-images.githubusercontent.com/164050/206758402-10a06322-0cba-468d-96bd-39888883dfe5.png)

![CleanShot 2022-12-09 at 09 21 32@2x](https://user-images.githubusercontent.com/164050/206757964-ab77e294-cc83-4a3e-83de-b89ac3f0c72e.png)
