### ISSUE TITLE
[Query] Is underscore a part of the UUID generated by this module?

### ISSUE THREAD

**Issue by nandita121189** [uuidjs/uuid#680]
### Before you begin...

- [X] I have searched the existing issues
- [X] I am not using version 13.x of node  (if so, please upgrade)

### Description of the problem

I need to create a UUID without any special characters. Can you please advise, the UUID generated by this module consists of which all characters? If it includes special characters, is there a way to remove those special characters while generating a UUID?

**Comment by broofa** [comment]
All UUIDs consist of 32 hexadecimal digits with four hyphens at well-established locations.  E.g. `f81d4fae-7dec-11d0-a765-00a0c91e6bf6`

As this is the only valid string form allowed by RFC4122, this library does not support converting to other forms of (non-UUID) ids.

See also https://github.com/uuidjs/uuid/issues/177
