### ISSUE TITLE
Add exports config in package.json

### ISSUE THREAD

**Issue by tobiasdiez** [uuidjs/uuid#691]
### Feature description

Some bundlers require a correct [export](https://nodejs.org/api/packages.html#conditional-exports) declaration in `package.json` to choose between cjs/esm.

### Additional information

Could also help with https://github.com/uuidjs/uuid/issues/678.

**Comment by broofa** [comment]
`exports` are already defined. `export` isn't a package.json thing.

**Comment by tobiasdiez** [comment]
You are right, I was still using an older version. Sorry for the noise!
