### ISSUE TITLE
URL overridden?

### ISSUE THREAD

**Issue by Konglomneshued** [uuidjs/uuid#693]
I have issue building an app I am making.

I narrowed down the culprit

![Image](https://user-images.githubusercontent.com/94726665/223301883-0b17a939-e4c5-4886-b177-4d88b345aea5.png)

![image](https://user-images.githubusercontent.com/94726665/223301901-c46d1235-aec1-44b5-aebf-e7992c9b59d4.png)

Is URL overridden here by this package?
![image](https://user-images.githubusercontent.com/94726665/223302497-5d3fe1bd-d062-45c9-9346-68181154f949.png)

**Comment by broofa** [comment]
Any chance you've got a `import {URL} from 'uuid'` statement in there somewhere?

Failing that, this looks like a bug in your bundler.  While `uuid` does export a `URL` property, it's never assigned to the global object.
