### ISSUE TITLE
[BUG] npm rebuild runs "prepare" hook, switch to postinstall?

### ISSUE THREAD

**Issue by simllll** [uuidjs/uuid#698]
### Before you begin...

- [X] I have searched the existing issues
- [X] I am not using version 13.x of node  (if so, please upgrade)

### Description of the problem

It's not the first time, but now again it happens in my setup that the prepare script gets (wrongly) executed and fails.

We are usingg pnpm and the deploy command, after putting everything togtether I would like to run npm rebuild to ensure all native deps are valid. But this fails because uuid's prepare hook is executed.

```
#6 DONE 63.2s
#7 [5/5] RUN npm rebuild --ignore-scripts && 	apk del .build-deps
#7 sha256:2814742e29362ea6ae655a3538ce56fb42089bf2f112a1059bd1daf9818e22d1
#7 66.39 npm ERR! code 127
#7 66.39 npm ERR! path /app/node_modules/.pnpm/uuid@9.0.0/node_modules/uuid
#7 66.70 npm ERR! command failed
#7 66.70 npm ERR! command sh -c cd $( git rev-parse --show-toplevel ) && husky install
#7 66.70 npm ERR! fatal: not a git repository (or any of the parent directories): .git
#7 66.70 npm ERR! /bin/sh: husky: not found
#7 67.00 
#7 67.00 npm ERR! A complete log of this run can be found in:
#7 67.00 npm ERR!     /root/.npm/_logs/2023-03-19T10_48_40_643Z-debug-0.log
#7 ERROR: executor failed running [/bin/sh -c npm rebuild --ignore-scripts && 	apk del .build-deps]: exit code: 127
------
 > [5/5] RUN npm rebuild && 	apk del .build-deps:
------
executor failed running [/bin/sh -c npm rebuild --ignore-scripts && 	apk del .build-deps]: exit code: 127
```

Is there any specifc reason why this is insie prepare? Wouldn't "**postinstall**" not be even better for the 
`sh -c cd $( git rev-parse --show-toplevel ) && husky install` command?

### Recipe for reproducing

`
run "npm rebuild" in a setup where you do not have a git environment checked out.

### Additional information

I also tried running it wiht  --ignore-scripts, but this doesn't make any difference somehow.

### Environment

docker node 18

**Comment by simllll** [comment]
are you sure it's about the build script and not about the prepare script? 

The weird thing I thought is the reason is that sometimes it seems the prepare script is even run on install. See https://docs.npmjs.com/cli/v9/using-npm/scripts
NOTE: If a package being installed through git contains a prepare script, its dependencies and devDependencies will be installed, and the prepare script will be run, before the package is packaged and installed. 

It seems somehow it assumes that it is a git package in my environment I guess?

The commands i run:
$ pnpm i
$ pnpm deploy --prod --filter package ./output
Copy the whole Output inside a docker alpine image (it contains the node_modules folder)
Run npm rebuild inside docker.

Maybe it's caused by another dependency that uses UUID, i will look into that tomorrow.

Regarding prepare and postinstall I have to agree though, I'm not sure what brought to this suggestion 🙈

**Comment by broofa** [comment]
I think that NOTE only applies when pulling a module directly from a git repo.  E.g. if you had the `uuid` dependency in package.json declared as `"uuid": "git+https://github.com/uuidjs/uuid.git"`.... which I assume isn't the case here.

**Comment by simllll** [comment]
Nice finding of @pkerschbaum https://docs.npmjs.com/cli/v9/using-npm/scripts#npm-rebuild

> [npm` rebuild](https://docs.npmjs.com/cli/v9/commands/npm-rebuild)
> preinstall
> install
> postinstall
> prepare
> prepare is only run if the current directory is a symlink (e.g. with linked packages)

**Comment by broofa** [comment]
Interesting. I guess the assumption there is that symlinks reference local / unpublished modules.  E.g. as you'd get with `npm link` or `yarn` workspaces.

Note: In my test, above I used `npm` to install `uuid`, which doesn't create a symlink.  But even if I use `pnpm` for the install (and, thus, create a symlink) `pnpm rebuild` still works for me:
```bash
$ npx pnpm init
...

$ npx pnpm install uuid
...

$ ls -lF node_modules/uuid
lrwxr-xr-x  1 kieffer  wheel  34 Mar 20 09:25 node_modules/uuid@ -> .pnpm/uuid@9.0.0/node_modules/uuid

$ npx pnpm rebuild

$
```

**Comment by pkerschbaum** [comment]
regarding `pnpm rebuild` I created this issue: https://github.com/pnpm/pnpm/issues/6268
