### ISSUE TITLE
[BUG] The test failed on the latest node version `rng` `Browser without crypto.getRandomValues()'` test fail

### ISSUE THREAD

**Issue by rluvaton** [uuidjs/uuid#708]
### Before you begin...

- [X] I have searched the existing issues
- [X] I am not using version 13.x of node  (if so, please upgrade)

### Description of the problem

The test is failing on the latest node version (19.9.0):
https://github.com/uuidjs/uuid/blob/6eef540aa3407b15e1e7573f45ff17098e9343ea/test/unit/rng.test.js#L15-L19

as crypto is [globally available](https://nodejs.org/api/globals.html#crypto:~:text=v19.0.0-,No%20longer%20behind%20%2D%2Dexperimental%2Dglobal%2Dwebcrypto%20CLI%20flag.,-v17.6.0%2C%20v16.15.0), which causes the CITGM tests in node to fail.

related PR:
- https://github.com/nodejs/node/pull/47413

### Recipe for reproducing

run:

```bash
nvm install 19.9.0
nvm use 19.9.0
npm test
```

**Comment by LinusU** [comment]
Thank you for bringing this to our attention, potential fix is up here: https://github.com/uuidjs/uuid/pull/709
