### ISSUE TITLE
[BUG] UUID validator identifies uuid as invalid

### ISSUE THREAD

**Issue by delijah** [uuidjs/uuid#712]
### Before you begin...

- [X] I have searched the existing issues
- [X] I am not using version 13.x of node  (if so, please upgrade)

### Description of the problem

The validation function considers the following uuid being invalid: b46a70e0-dea8-11ed-0000-000000000000

About 5 popular online uuid validators say this is a valid uuid. Also the `validator` npm-package says this uuid is valid.

### Recipe for reproducing

[https://codesandbox.io/s/wizardly-margulis-l32syf?file=/src/App.js](https://codesandbox.io/s/wizardly-margulis-l32syf?file=/src/App.js)

**Comment by LinusU** [comment]
It doesn't look valid to me, the variant is set as `0` which seems wrong.

Look at the description about **N** here: https://en.wikipedia.org/wiki/Universally_unique_identifier#Format

**Comment by delijah** [comment]
Just had a quick look at the document. Isn't this the variant-0, which still is supported for backwards compatibility? Or am i getting it wrong?
