### ISSUE TITLE
Double spaces in the deprecation message

### ISSUE THREAD

**Issue by Lui22** [uuidjs/uuid#720]
### Feature description

The deprecation message contains double spaces:
```
Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
```
between the `upgrade to` and after each end of the sentence.
So I propose to remove the extra spaces

### Additional information

Fixed message:
```
Please upgrade to version 7 or higher. Older versions may use Math.random() in certain circumstances, which is known to be problematic. See https://v8.dev/blog/math-random for details.
```

**Comment by broofa** [comment]
Fixed.  Thanks for the report!
![CleanShot 2023-06-17 at 06 40 08@2x](https://github.com/uuidjs/uuid/assets/164050/d0458d64-21f1-4e30-874f-f63c83ec8989)
