### ISSUE TITLE
NPM Deprication Message is ambiguous

### ISSUE THREAD

**Issue by WikipediaBrown** [uuidjs/uuid#723]
### Feature description

The description from `NPM` when installing `UUID` is ambiguous and leads to several versions of misunderstanding.

The warning says this: `Older versions may use Math.random() in certain circumstances, which is known to be problematic.`

The term `problematic` is a weasel word that has no empirical meaning (contextual or otherwise) and causes the reader to have to develop their own idea of what the sentence means. 

If the use of `Math.random()` is a security vulnerability, then say so. Not saying so harms end users directly and on purpose.

If the use of `Math.random()` is preferred over other solutions because of efficiency, then say so. Not saying so harms products and development teams directly and on purpose.

I can go on here but being ambiguous in this fashion raises red flags. Be clear about the flags you raise. 

### Additional information

Full text:

```npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.```

**Comment by LinusU** [comment]
> If the use of `Math.random()` is a security vulnerability, then say so. 

I think that this depends on the context which the `uuid` library is used, so it's very hard to make a general statement...

Do you have a proposal on what to change the message to?

**Comment by broofa** [comment]
> leads to several versions of misunderstanding

Unless readers fail to understand that they shouldn't be using versions <= 3.4.0, there's no misunderstanding.

> problematic is a weasel word

Only in contexts where it's appropriate to elaborate in more detail.  Deprecation messages should be concise and to the point, which the current one is.   It also includes a link with details for readers interested in understanding what we mean by "problematic".

> Do you have a proposal on what to change the message to?

Don't bother.   Current message is fine and I'm not interested in wasting time wordsmithing this.
