### ISSUE TITLE
Sponsored issue: Incremental UUID

### ISSUE THREAD

**Issue by Anushka7310** [uuidjs/uuid#737]
I would like to request the addition of a feature that allows for the generation of incremental IDs using the UUID library. Currently, the project supports UUID generation, but it doesn't provide an option for generating sequential or incremental IDs.

This feature would be particularly useful in scenarios where it's necessary to have both the uniqueness of UUIDs and the sequential ordering of IDs, such as in database records.

## Priority Support

- @anushka7310 is using  [Mintycode](https://mintycode.io) to fund this issue.
- If you would like to accept ![amount](https://imageupload.io/ib/zwkd2EaAY6YpPsg_1693209112.png) bounty for solving this issue join [Mintycode](https://mintycode.io/profile?action=CREATOR_SUPPORT_MODAL&requestId=a26dbe51-0019-4e43-a04d-a83d67936eba&owner=uuidjs&name=uuid).
- Thank you in advance for helping.

[![mintycode](https://imageupload.io/ib/LvxMwrPxam1JW9e_1693210482.png)](https://mintycode.io)

**Comment by broofa** [comment]
What you're describing is the new UUID v7 format.   See https://github.com/uuidjs/uuid/pull/681

Please be aware that to the extent you need IDs with characteristics that fall outside of RFC4122, you'll need to look elsewhere for a solution.  This project deals *only* with RFC4122 UUIDs.
