### ISSUE TITLE
[question] is posible decode uuid to data back ?

### ISSUE THREAD

**Issue by YovanggaAnandhika** [uuidjs/uuid#740]
### Feature description

```typescript

import { v5 } from "uuid";

   v5(<isData>, <namespace>); /** -> 32ABF614-5646-5448-B514-EE0E3DB6F833 **/

```

now, is possible get back **isData** from 32abf614-5646-5448-b514-ee0e3db6f833 to **isData** ??

**Comment by broofa** [comment]
No, v5 uses a SHA-1 hash, which is not reversible.
https://stackoverflow.com/questions/2235079/is-it-possible-to-reverse-a-sha-1-hash
