### ISSUE TITLE
validate method returns false for a valid UUID

### ISSUE THREAD

**Issue by shijumon** [uuidjs/uuid#742]
### Before you begin...

- [X] I have searched the existing issues
- [X] I am not using version 13.x of node  (if so, please upgrade)

### Description of the problem

call validate method for the UUID : caa8b54a-eb5e-4134-7ae2-a3946a428ec7
It retuns false

### Recipe for reproducing

```bash
call validate method for the UUID : caa8b54a-eb5e-4134-7ae2-a3946a428ec7
```

**Comment by broofa** [comment]
`variant` field is invalid.  Must be 8, 9, a or b per RFC4122.

![CleanShot 2024-01-11 at 05 36 02@2x](https://github.com/uuidjs/uuid/assets/164050/040c0759-6b70-44c7-8011-64b0c38fee4c)

**Comment by TheAnarchoX** [comment]
No it does not, NCS backward compatible UUID's are a perfectly fine variant of v4 UUID's, as specified in the RFC. Yes they are reserved for backwards compatibility but that does not make them invalid, nowhere in the RFC does it say that variants other than 8-b are. Same goes for so called GUID's (Microsoft's UUID's, variant c-d). I think a documentation update is in place to clarify which variants it can and can't validate. 

Also: this package is unusable for anyone trying to validate anything generated by a Microsoft backed tech, e.g. .NET, SQL Server. Please make this clear somewhere

**Comment by broofa** [comment]
The only place RFC4122 alludes to NCS ids is to reserve the variants they are known to use NCS.  It does not speak to the their format or any other characteristics of them that may or may not make them "valid".   The same can be said of the "Reserved, Microsoft" variant (`0b110`).  

[Per the spec](https://datatracker.ietf.org/doc/html/rfc4122#section-4.1.1), the `0b10x` is the only variant specified by RFC4122.  I.e. Ids with that variant are the only ones that can be validated with any degree of confidence.

If you want to validate NCS ids, you'll need to do that yourself.  That format isn't part of RFC4122.  Thus, it's not in-scope here.

**Comment by broofa** [comment]
@TheAnarchoX If you don't mind my asking, what application are you working on that's using NCS uuids?  This is the first time in over a decade of maintaining this project that I've heard of anyone using them.  😮

**Comment by TheAnarchoX** [comment]
Missed your comment, it's just .NET 6 running EF Core and Azure SQL Server, our UUIDs are mostly database generated, I believe some are generate using .NET (Guid.NewGuid()) so nothing crazy tbh
