### ISSUE TITLE
uuidv6 has been officially adopted by the IETF

### ISSUE THREAD

**Issue by gregkonush-sequoia** [uuidjs/uuid#748]
### Feature description

Is there plans on creating implementation of uuidv6, uuidv7, uuidv8? [uuid6](https://github.com/uuid6/uuid6-ietf-draft) repo indicates that their work has been adopted by the IETF.

**Comment by BurningEnlightenment** [comment]
Indeed, it has been published as [RFC 9562](https://www.rfc-editor.org/rfc/rfc9562) which officially obsoletes [RFC 4122](https://www.rfc-editor.org/rfc/rfc4122).

**Comment by broofa** [comment]
Yes, we'll be adding support for all new RFC9562 formats.  See https://github.com/uuidjs/uuid/pull/681

I just need to find time to do a proper review and update to that PR to make sure it aligns with the final spec, and deploy a new release.

FWIW, I actually need v7 for my actual paying job, so this will happen "soon-ish", but I can't commit to an exact ETA at this time.

**Comment by broofa** [comment]
Now tracking this in #749
