### ISSUE TITLE
[BUG] Module '"uuid"' has no exported member 'v7'.ts(2305)

### ISSUE THREAD

**Issue by alka7ex** [uuidjs/uuid#773]
### Before you begin...

- [X] I have searched the existing issues
- [X] I am not using version 13.x of node  (if so, please upgrade)

### Description of the problem

Hi Guys 

I got an issues related with types for v7, the functionalities is working fine but it has some types complain stating that

Module '"uuid"' has no exported member 'v7'.ts(2305)

![image](https://github.com/uuidjs/uuid/assets/18338838/5b40b4d5-129c-4ae4-8ecc-81bfb290c415)

**Comment by broofa** [comment]
From the Bug Report template:

# Failure to provide a [Minimal, Complete, and Verifiable](https://stackoverflow.com/help/minimal-reproducible-example) example will result in this issue being closed without further review

**Comment by sir-dunxalot** [comment]
I ran into this issue... Check if other dependencies are using older versions of `uuid` (e.g. `"uuid": "^9.0.1"`). You can verify this by searching your `package-lock.json` for `uuid`. In my case, an older version of `@types/uuid` was a dependency and it was creating a version mis-match between `uuid`, which I had installed and `@types/uuid`, which was installed by other dependencies (e.g. `@azure/core-http`). I was able to resolve this issue by manually installing an updated, matching version of `@types/uuid` (e.g. `npm install @types/uuid@10`).

**Comment by broofa** [comment]
FWIW, `uuid@beta` (uuid@11 prerelease) has built-in TS types, so there should no longer be a need for `@types/uuid` moving forward.
