### ISSUE TITLE
[BUG] CLI for uuid@10 does not work on Windows.

### ISSUE THREAD

**Issue by tjsr** [uuidjs/uuid#785]
### Before you begin...

- [X] I have searched the existing issues
- [X] I am not using version 13.x of node  (if so, please upgrade)

### Description of the problem

It appears that uuid@10 breaks or removes the CLI version of the tool, but only on Windows. It's also working using uuid@9, and the nix versions all work fine.

### Recipe for reproducing

```
H:\dev\uuid>npx uuid@10
'uuid' is not recognized as an internal or external command,
operable program or batch file.

H:\dev\uuid>npx uuid@9
d3d618e5-9c52-4acd-aa86-1bc2ac0a4193
```

Under WSL:
```bash
tjsr@tjsr:/mnt/h/dev$ npx uuid@10
Need to install the following packages:
uuid@10.0.0
Ok to proceed? (y) y

18e5951e-fc2e-4b1e-9a90-b5cd12a29704
```

### Additional information

Also tested this within WSL (worked), and also ran it within codespaces.  Unfortunately do not have the time to investigate further at this time.

For the moment, the workaround would be to just specify using uuid@9.

### Environment

```
Need to install the following packages:
envinfo@7.13.0
Ok to proceed? (y) y


  System:
    OS: Windows 11 10.0.22631
    CPU: (16) x64 AMD Ryzen 7 3700X 8-Core Processor
    Memory: 16.39 GB / 63.93 GB
  Binaries:
    Node: 20.15.0 - C:\Program Files\nodejs\node.EXE
    npm: 10.8.2 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Chromium (127.0.2651.74)
    Internet Explorer: 11.0.22621.3527
```

**Comment by broofa** [comment]
FWIW, I don't have ready access to a Windows environment so my ability to test/verify/fix this is limited. A couple thoughts, however ...

Possibly an issue with npm/npx?   E.g. does  `uuid` work if you do a local-install of `uuid`, something like ...

```bash
$ npm install uuid@10

$ ./node_modules/.bin/uuid
97ee1d33-75e4-472b-8bd2-4c02f555aeb6
```

Possibly an issue with the npm/npx version?   E.g. does `uuid` work if you run a previous npx version, something like ...
```bash
$ nvm use 16
Now using node v16.20.2 (npm v8.19.4)

$ npx --version
8.19.4

$ npx uuid@10
d8110eab-b944-461e-a140-0e94743e73b4
```

**Comment by tjsr** [comment]
Re "But maybe the uuid CLI just isn't that widely used?"
- Could very well also be that it's rarely used in scripts on Windows or cross-platform environments.  IF/where the CLI is being used, I would hazard a guess it's mostly in nix environments.
I mean, I use it in pretty much every project extensively (about 12 active ones I'm working on all use it), and it's the first time I've encountered this, or used the cli tool - and do all my dev on Windows locally.


Anyhow,

From an existing project that already utilised uuid:
```
H:\dev\tagtool>npm ls uuid
@tjsr/tagtool@0.1.0 H:\dev\tagtool
├─┬ @tjsr/express-server-helper@0.0.3
│ └─┬ @tjsr/user-session-middleware@0.0.24
│   └── uuid@10.0.0 deduped
├─┬ @tjsr/testutils@0.0.6
│ └── uuid@10.0.0 deduped
├─┬ @tjsr/user-session-middleware@0.0.25
│ └── uuid@10.0.0 deduped
└── uuid@10.0.0

H:\dev\tagtool>node_modules\.bin\uuid
77e2d0e6-7136-4c18-bd26-b9af48948f70
```

But now it gets interesting, taking from your idea. From taht same terminal - this was a different one I ran the original bug report on (but still in the same vscode instance):

```
H:\dev\tagtool>node --version
v20.15.0

H:\dev\tagtool>nvm ls

  * 20.15.0 (Currently using 64-bit executable)
    20.14.0
    20.13.1
    20.12.2
    20.11.0
    20.9.0
    18.15.0
    18.13.0
```

```
H:\dev\tagtool>nvm use 20.12.2
Now using node v20.12.2 (64-bit)

H:\dev\tagtool>npx uuid@10
5af752ff-d38f-4cb9-97cc-10e9adacdf80

H:\dev\tagtool>cd ..

H:\dev>npx uuid@10
Need to install the following packages:
uuid@10.0.0
Ok to proceed? (y) y

30b72bb5-3730-4e68-a9d6-0cde00869f02

H:\dev>nvm use 20.15.0
Now using node v20.15.0 (64-bit)

H:\dev>npx uuid@10
b3980e8a-f2dc-4f9a-9af6-b9d30578d82a
```

So we've taken the same version/environment/installation, seen it fail, switched to another version, had that work, switched back to the previously broken version... and it works.


I thought "Okay, let's try another terminal" - and it gets wacky.
```
H:\dev\uuid>npx uuid@9
07a00fe5-091e-4b54-8fe2-ce17b471c4f7

H:\dev\uuid>npx uuid@10
'uuid' is not recognized as an internal or external command,
operable program or batch file.

H:\dev\uuid>nvm ls

  * 20.15.0 (Currently using 64-bit executable)
    20.14.0
    20.13.1
    20.12.2
    20.11.0
    20.9.0
    18.15.0
    18.13.0

H:\dev\uuid>nvm use 20.12.2
Now using node v20.12.2 (64-bit)

H:\dev\uuid>npx --version
10.8.0

H:\dev\uuid>npx uuid@10
'uuid' is not recognized as an internal or external command,
operable program or batch file.

H:\dev\uuid>nvm use 20.15.0
Now using node v20.15.0 (64-bit)

H:\dev\uuid>npx uuid@10     
'uuid' is not recognized as an internal or external command,
operable program or batch file.

H:\dev\uuid>npx --version
10.8.2

H:\dev\uuid>
```

Probably getting a bit far reaching now, but doesn't seem to be anything funny going on here either:
```
H:\dev\uuid>type "C:\Program Files\nodejs\npx.cmd"
@ECHO off
GOTO start
:find_dp0
SET dp0=%~dp0
EXIT /b
:start
SETLOCAL
CALL :find_dp0

IF EXIST "%dp0%\node.exe" (
  SET "_prog=%dp0%\node.exe"
) ELSE (
  SET "_prog=node"
  SET PATHEXT=%PATHEXT:;.JS;=;%
)

endLocal & goto #_undefined_# 2>NUL || title %COMSPEC% & "%_prog%"  "%dp0%\node_modules\npm\bin\npx-cli.js" %*
```

So we seem to have some kind of inconsistent environment in different terminals where one recognises uuid@10 and the other environments do not.

As one last check, from a clean terminal:

```
Microsoft Windows [Version 10.0.22631.3880]
(c) Microsoft Corporation. All rights reserved.

H:\dev\lwdb>npx uuid@10
'uuid' is not recognized as an internal or external command,
operable program or batch file.
```

Finally, I tried it on my second system/notebook - which worked fine in a fresh terminal.  So yep, definitely something environment related.  Pretty bizarre it only happens for uuid (that I've found) though.

Let me know what other replication ideas you can think of - will get back to you in about 8 hours if there's more I can provide.

**Comment by broofa** [comment]
Huh. This "feels" more like an npx/npm or environment issue than a uuid issue.  Especially since the behavior is intermittent and uuid isn't doing anything clever, or even different from uuid@9 (that I recall), as far as how the CLI is set up.

I'll leave this open for the time being, but unless you can identify a specific issue with this project there's nothing actionable here (yet).
