### ISSUE TITLE
[BUG] Fix #764 not published yet

### ISSUE THREAD

**Issue by defaultbranch** [uuidjs/uuid#790]
### Before you begin...

- [X] I have searched the existing issues
- [X] I am not using version 13.x of node  (if so, please upgrade)

### Description of the problem

I see you have fixed #764, however, the latest available release <https://www.npmjs.com/package/uuid/v/10.0.0> still has this bug.

Can you please release the fix #764 (and whatever else) on npmjs.com? Thanks!

**Comment by broofa** [comment]
Working on it.  There's an issue with the BrowserStack CI checks, and haven't had the time to work that out yet.

P.S.  For future reference, please don't create an issue just to report an issue with an existing issue.  Just comment on the issue.

**Comment by broofa** [comment]
You can folllow #789 for updates to the BS issue.
