### ISSUE TITLE
Export options types

### ISSUE THREAD

**Issue by skycoop** [uuidjs/uuid#832]
### Feature description

I was previously using the options type provided in the DefinitelyTyped package (i.e. `V7Options`) to type a function that passed through options to the UUID constructor. I would love if those options types were exported by UUID v11

### Additional information

I can work around the issue by declaring a type `type V7Options = Parameters<typeof v7>[0]`, but it's a little clunky compared to having access to the type directly

**Comment by broofa** [comment]
I'd be happy to take a look at a PR. :-) 

Note: Such a PR should treat the `options` arg consistently for all v1-v7 methods similarly)
