### ISSUE TITLE
[BUG] <Type Error>

### ISSUE THREAD

**Issue by komeilm76** [uuidjs/uuid#839]
### Before you begin...

- [X] I have searched the existing issues
- [X] I am not using version 13.x of node  (if so, please upgrade)

### Description of the problem

in last version 
 i give this error on building.
 
```
node_modules/uuid/dist/cjs/index.d.ts:1:1 - error TS1383: Only named exports may use 'export type'.
1 export type * from './types.js';
```

in version:11.0.2  work without problem. but in last version is not work

**Comment by broofa** [comment]
Duplicate #837
