### ISSUE TITLE
[BUG] validate function fails on a valid uuidv7 generated uuid

### ISSUE THREAD

**Issue by ericlau-solid** [uuidjs/uuid#851]
### Before you begin...

- [X] I have searched the existing issues
- [X] I am not using version 13.x of node  (if so, please upgrade)

### Description of the problem

A valid uuid (generated using uuidv7) does not pass the validation function check.

### Recipe for reproducing

```bash
Run uuid.validate on the following input:

01941ebf-a4d6-71be-a576-df5efa0f5008

Function returns false, but it is clearly a valid uuidv7 generated string
```

**Comment by broofa** [comment]
```bash
$ node -e "console.log(require('uuid').validate('01941ebf-a4d6-71be-a576-df5efa0f5008'))"
true

$ npm ls uuid
foo@ /private/tmp/foo
`-- uuid@11.0.3
```

![CleanShot 2024-12-31 at 14 59 24@2x](https://github.com/user-attachments/assets/212f8f5d-6d6d-4385-82ed-586be8f93484)

**Comment by ericlau-solid** [comment]
Ugh. Sorry. I must have a really old uuid lib somewhere. Apologies for time wasting.

**Comment by anhcao142** [comment]
@broofa Hi, how about this one `d4c884e8-a011-7030-25f5-3fce11af3ec3`, this site shows it valid. But it returns false with the validate function

<img width="823" alt="Image" src="https://github.com/user-attachments/assets/52dc70ce-fb6e-497b-b46e-8f1700818841" />

**Comment by broofa** [comment]
@anhcao142:

![Image](https://github.com/user-attachments/assets/1d073fb9-bb91-450a-8348-1371e2b8e18a)
